; This file was automatically generated by dialogformatter.py
    
.macro inleveldialogueheader
	.byte   0x0C,0x00,0x78,0x50, \
            0xB0,0x28,0x44,0x10, \
            0xD0,0x28,0x44,0x10, \
			0xF0,0x28,0x44,0x10, \
            0x10,0x28,0x44,0x10, \
            0x30,0x28,0x44,0x10, \
            0x50,0x28,0x44,0x10, \
            0xB0,0x48,0x14,0x04, \
            0xD0,0x48,0x14,0x04, \
			0xF0,0x48,0x14,0x04, \
            0x10,0x48,0x14,0x04, \
            0x30,0x48,0x14,0x04, \
            0x50,0x48,0x14,0x04
.endmacro    

.macro inleveltitleheader3 ; 3 blocks, centered
    .byte   0x03,0x20,0x78,0x50, \
            0xD0,0xF8,0x24,0x08, \
            0xF0,0xF8,0x24,0x08, \
            0x10,0xF8,0x24,0x08
.endmacro

.macro inleveltitleheader4 ; 4 blocks, centered
    .byte   0x04,0x20,0x68,0x50, \
            0xD0,0xF8,0x24,0x08, \
            0xF0,0xF8,0x24,0x08, \
            0x10,0xF8,0x24,0x08, \
            0x30,0xF8,0x24,0x08
.endmacro

.macro inleveltitleheader5 ; 5 blocks, centered
    .byte   0x05,0x20,0x58,0x50, \
            0xD0,0xF8,0x24,0x08, \
            0xF0,0xF8,0x24,0x08, \
            0x10,0xF8,0x24,0x08, \
            0x30,0xF8,0x24,0x08, \
            0x50,0xF8,0x24,0x08
.endmacro

.org 0x082AAE34
.region 0x082E4E24 - org() ; space taken up by original in-level titles + text boxes
	@training1Title: :: inleveltitleheader3
	.incbin "graphics\inlevel\dumps\training1title.dmp" :: .align
	@training2Title: :: inleveltitleheader3
	.incbin "graphics\inlevel\dumps\training2title.dmp" :: .align
	@training3Title: :: inleveltitleheader3
	.incbin "graphics\inlevel\dumps\training3title.dmp" :: .align
	@training4Title: :: inleveltitleheader3
	.incbin "graphics\inlevel\dumps\training4title.dmp" :: .align
	@training5Title: :: inleveltitleheader3
	.incbin "graphics\inlevel\dumps\training5title.dmp" :: .align
	@village1Title: :: inleveltitleheader3
	.incbin "graphics\inlevel\dumps\village1title.dmp" :: .align
	@village2Title: :: inleveltitleheader3
	.incbin "graphics\inlevel\dumps\village2title.dmp" :: .align
	@village3Title: :: inleveltitleheader3
	.incbin "graphics\inlevel\dumps\village3title.dmp" :: .align
	@village4Title: :: inleveltitleheader3
	.incbin "graphics\inlevel\dumps\village4title.dmp" :: .align
	@village5Title: :: inleveltitleheader3
	.incbin "graphics\inlevel\dumps\village5title.dmp" :: .align
	@village5aTitle: :: inleveltitleheader3
	.incbin "graphics\inlevel\dumps\village5atitle.dmp" :: .align
	@village4aTitle: :: inleveltitleheader3
	.incbin "graphics\inlevel\dumps\village4atitle.dmp" :: .align
	@village4bTitle: :: inleveltitleheader3
	.incbin "graphics\inlevel\dumps\village4btitle.dmp" :: .align
	@flower1Title: :: inleveltitleheader3
	.incbin "graphics\inlevel\dumps\flower1title.dmp" :: .align
	@flower2Title: :: inleveltitleheader3
	.incbin "graphics\inlevel\dumps\flower2title.dmp" :: .align
	@flower3Title: :: inleveltitleheader3
	.incbin "graphics\inlevel\dumps\flower3title.dmp" :: .align
	@flower4Title: :: inleveltitleheader3
	.incbin "graphics\inlevel\dumps\flower4title.dmp" :: .align
	@flower5Title: :: inleveltitleheader5
	.incbin "graphics\inlevel\dumps\flower5title.dmp" :: .align
	@flower5aTitle: :: inleveltitleheader3
	.incbin "graphics\inlevel\dumps\flower5atitle.dmp" :: .align
	@flower3aTitle: :: inleveltitleheader5
	.incbin "graphics\inlevel\dumps\flower3atitle.dmp" :: .align
	@flower3bTitle: :: inleveltitleheader3
	.incbin "graphics\inlevel\dumps\flower3btitle.dmp" :: .align
	@clock1Title: :: inleveltitleheader3
	.incbin "graphics\inlevel\dumps\clock1title.dmp" :: .align
	@clock2Title: :: inleveltitleheader3
	.incbin "graphics\inlevel\dumps\clock2title.dmp" :: .align
	@clock3Title: :: inleveltitleheader3
	.incbin "graphics\inlevel\dumps\clock3title.dmp" :: .align
	@clock4Title: :: inleveltitleheader5
	.incbin "graphics\inlevel\dumps\clock4title.dmp" :: .align
	@clock5Title: :: inleveltitleheader4
	.incbin "graphics\inlevel\dumps\clock5title.dmp" :: .align
	@clock4aTitle: :: inleveltitleheader5
	.incbin "graphics\inlevel\dumps\clock4atitle.dmp" :: .align
	@clock3aTitle: :: inleveltitleheader4
	.incbin "graphics\inlevel\dumps\clock3atitle.dmp" :: .align
	@clock3bTitle: :: inleveltitleheader3
	.incbin "graphics\inlevel\dumps\clock3btitle.dmp" :: .align
	@magic1Title: :: inleveltitleheader3
	.incbin "graphics\inlevel\dumps\magic1title.dmp" :: .align
	@magic2Title: :: inleveltitleheader3
	.incbin "graphics\inlevel\dumps\magic2title.dmp" :: .align
	@magic3Title: :: inleveltitleheader3
	.incbin "graphics\inlevel\dumps\magic3title.dmp" :: .align
	@magic4Title: :: inleveltitleheader3
	.incbin "graphics\inlevel\dumps\magic4title.dmp" :: .align
	@magic5Title: :: inleveltitleheader3
	.incbin "graphics\inlevel\dumps\magic5title.dmp" :: .align
	@magic6Title: :: inleveltitleheader4
	.incbin "graphics\inlevel\dumps\magic6title.dmp" :: .align
	@magic4aTitle: :: inleveltitleheader4
	.incbin "graphics\inlevel\dumps\magic4atitle.dmp" :: .align
	@magic4aaTitle: :: inleveltitleheader4
	.incbin "graphics\inlevel\dumps\magic4aatitle.dmp" :: .align
	@magic4abTitle: :: inleveltitleheader3
	.incbin "graphics\inlevel\dumps\magic4abtitle.dmp" :: .align
	@neo1Title: :: inleveltitleheader5
	.incbin "graphics\inlevel\dumps\neo1title.dmp" :: .align
	@neo2Title: :: inleveltitleheader3
	.incbin "graphics\inlevel\dumps\neo2title.dmp" :: .align
	@neo3Title: :: inleveltitleheader3
	.incbin "graphics\inlevel\dumps\neo3title.dmp" :: .align
	@neo4Title: :: inleveltitleheader3
	.incbin "graphics\inlevel\dumps\neo4title.dmp" :: .align

	@training1Text: :: inleveldialogueheader
	.incbin "graphics\inlevel\dumps\training1.dmp" :: .align
	@training2Text: :: inleveldialogueheader
	.incbin "graphics\inlevel\dumps\training2.dmp" :: .align
	@training3Text: :: inleveldialogueheader
	.incbin "graphics\inlevel\dumps\training3.dmp" :: .align
	@training4Text: :: inleveldialogueheader
	.incbin "graphics\inlevel\dumps\training4.dmp" :: .align
	@training5Text: :: inleveldialogueheader
	.incbin "graphics\inlevel\dumps\training5.dmp" :: .align
	@village1Text: :: inleveldialogueheader
	.incbin "graphics\inlevel\dumps\village1.dmp" :: .align
	@village2Text: :: inleveldialogueheader
	.incbin "graphics\inlevel\dumps\village2.dmp" :: .align
	@village3Text: :: inleveldialogueheader
	.incbin "graphics\inlevel\dumps\village3.dmp" :: .align
	@village4Text: :: inleveldialogueheader
	.incbin "graphics\inlevel\dumps\village4.dmp" :: .align
	@village5Text: :: inleveldialogueheader
	.incbin "graphics\inlevel\dumps\village5.dmp" :: .align
	@village5aText: :: inleveldialogueheader
	.incbin "graphics\inlevel\dumps\village5a.dmp" :: .align
	@village4aText: :: inleveldialogueheader
	.incbin "graphics\inlevel\dumps\village4a.dmp" :: .align
	@village4bText: :: inleveldialogueheader
	.incbin "graphics\inlevel\dumps\village4b.dmp" :: .align
	@flower1Text: :: inleveldialogueheader
	.incbin "graphics\inlevel\dumps\flower1.dmp" :: .align
	@flower2Text: :: inleveldialogueheader
	.incbin "graphics\inlevel\dumps\flower2.dmp" :: .align
	@flower3Text: :: inleveldialogueheader
	.incbin "graphics\inlevel\dumps\flower3.dmp" :: .align
	@flower4Text: :: inleveldialogueheader
	.incbin "graphics\inlevel\dumps\flower4.dmp" :: .align
	@flower5Text: :: inleveldialogueheader
	.incbin "graphics\inlevel\dumps\flower5.dmp" :: .align
	@flower5aText: :: inleveldialogueheader
	.incbin "graphics\inlevel\dumps\flower5a.dmp" :: .align
	@flower3aText: :: inleveldialogueheader
	.incbin "graphics\inlevel\dumps\flower3a.dmp" :: .align
	@flower3bText: :: inleveldialogueheader
	.incbin "graphics\inlevel\dumps\flower3b.dmp" :: .align
	@clock1Text: :: inleveldialogueheader
	.incbin "graphics\inlevel\dumps\clock1.dmp" :: .align
	@clock2Text: :: inleveldialogueheader
	.incbin "graphics\inlevel\dumps\clock2.dmp" :: .align
	@clock3Text: :: inleveldialogueheader
	.incbin "graphics\inlevel\dumps\clock3.dmp" :: .align
	@clock4Text: :: inleveldialogueheader
	.incbin "graphics\inlevel\dumps\clock4.dmp" :: .align
	@clock5Text: :: inleveldialogueheader
	.incbin "graphics\inlevel\dumps\clock5.dmp" :: .align
	@clock4aText: :: inleveldialogueheader
	.incbin "graphics\inlevel\dumps\clock4a.dmp" :: .align
	@clock3aText: :: inleveldialogueheader
	.incbin "graphics\inlevel\dumps\clock3a.dmp" :: .align
	@clock3bText: :: inleveldialogueheader
	.incbin "graphics\inlevel\dumps\clock3b.dmp" :: .align
	@magic1Text: :: inleveldialogueheader
	.incbin "graphics\inlevel\dumps\magic1.dmp" :: .align
	@magic2Text: :: inleveldialogueheader
	.incbin "graphics\inlevel\dumps\magic2.dmp" :: .align
	@magic3Text: :: inleveldialogueheader
	.incbin "graphics\inlevel\dumps\magic3.dmp" :: .align
	@magic4Text: :: inleveldialogueheader
	.incbin "graphics\inlevel\dumps\magic4.dmp" :: .align
	@magic5Text: :: inleveldialogueheader
	.incbin "graphics\inlevel\dumps\magic5.dmp" :: .align
	@magic6Text: :: inleveldialogueheader
	.incbin "graphics\inlevel\dumps\magic6.dmp" :: .align
	@magic4aText: :: inleveldialogueheader
	.incbin "graphics\inlevel\dumps\magic4a.dmp" :: .align
	@magic4aaText: :: inleveldialogueheader
	.incbin "graphics\inlevel\dumps\magic4aa.dmp" :: .align
	@magic4abText: :: inleveldialogueheader
	.incbin "graphics\inlevel\dumps\magic4ab.dmp" :: .align
	@neo1Text: :: inleveldialogueheader
	.incbin "graphics\inlevel\dumps\neo1.dmp" :: .align
	@neo2Text: :: inleveldialogueheader
	.incbin "graphics\inlevel\dumps\neo2.dmp" :: .align
	@neo3Text: :: inleveldialogueheader
	.incbin "graphics\inlevel\dumps\neo3.dmp" :: .align
	@neo4Text: :: inleveldialogueheader
	.incbin "graphics\inlevel\dumps\neo4.dmp" :: .align
.endregion

.org 0x08029694 ; repointing in-level titles
	.word @training1Title
	.word @training2Title
	.word @training3Title
	.word @training4Title
	.word @training5Title
	.word @village1Title
	.word @village2Title
	.word @village3Title
	.word @village4Title
	.word @village5Title
	.word @village5aTitle
	.word @village4aTitle
	.word @village4bTitle
	.word @flower1Title
	.word @flower2Title
	.word @flower3Title
	.word @flower4Title
	.word @flower5Title
	.word @flower5aTitle
	.word @flower3aTitle
	.word @flower3bTitle
	.word @clock1Title
	.word @clock2Title
	.word @clock3Title
	.word @clock4Title
	.word @clock5Title
	.word @clock4aTitle
	.word @clock3aTitle
	.word @clock3bTitle
	.word @magic1Title
	.word @magic2Title
	.word @magic3Title
	.word @magic4Title
	.word @magic5Title
	.word @magic6Title
	.word @magic4aTitle
	.word @magic4aaTitle
	.word @magic4abTitle
	.word @neo1Title
	.word @neo2Title
	.word @neo3Title
	.word @neo4Title
.org 0x0802973C ; repointing in-level text boxes
	.word @training1Text
	.word @training2Text
	.word @training3Text
	.word @training4Text
	.word @training5Text
	.word @village1Text
	.word @village2Text
	.word @village3Text
	.word @village4Text
	.word @village5Text
	.word @village5aText
	.word @village4aText
	.word @village4bText
	.word @flower1Text
	.word @flower2Text
	.word @flower3Text
	.word @flower4Text
	.word @flower5Text
	.word @flower5aText
	.word @flower3aText
	.word @flower3bText
	.word @clock1Text
	.word @clock2Text
	.word @clock3Text
	.word @clock4Text
	.word @clock5Text
	.word @clock4aText
	.word @clock3aText
	.word @clock3bText
	.word @magic1Text
	.word @magic2Text
	.word @magic3Text
	.word @magic4Text
	.word @magic5Text
	.word @magic6Text
	.word @magic4aText
	.word @magic4aaText
	.word @magic4abText
	.word @neo1Text
	.word @neo2Text
	.word @neo3Text
	.word @neo4Text