; This file was automatically generated by formatsplashes.py

.macro pad
    .word 0x00 :: .align
.endmacro

; minigame splash struct array at 0x2E6D4 (16 bytes each)
; 1st dword (4 bytes) - palette pointer
; 2nd dword - tileset pointer (compressed)
; 3rd dword - compressed tileset size
; 4th dword - tilemap pointer (compressed)

; 0x02E6D4 ~ 0x02E6F4 - 2 blank entries

; 0x02E6F4 - crossfire palette would be here

.org 0x0802E6F8
    .word @crossfireTiles
    .word @crossfireTilesEnd - @crossfireTiles
    .word @crossfireMap

.org 0x0802E708
    .word @starTiles
    .word @starTilesEnd - @starTiles
    .word @starMap

.org 0x0802E718
    .word @bounceTiles
    .word @bounceTilesEnd - @bounceTiles
    .word @bounceMap

.org 0x0802E738
    .word @dotsTiles
    .word @dotsTilesEnd - @dotsTiles
    .word @dotsMap

.org 0x0802E748
    .word @grassTiles
    .word @grassTilesEnd - @grassTiles
    .word @grassMap

.org 0x0802E758
    .word @iceTiles
    .word @iceTilesEnd - @iceTiles
    .word @iceMap

.org 0x0802E768
    .word @skyTiles
    .word @skyTilesEnd - @skyTiles
    .word @skyMap

.org 0x0802E798
    .word @fallTiles
    .word @fallTilesEnd - @fallTiles
    .word @fallMap

.org 0x0802E7A8
    .word @magnetTiles
    .word @magnetTilesEnd - @magnetTiles
    .word @magnetMap

.org 0x0802E7B8
    .word @raceTiles
    .word @raceTilesEnd - @raceTiles
    .word @raceMap

.org 0x0802E7C8
    .word @shootTiles
    .word @shootTilesEnd - @shootTiles
    .word @shootMap

.org 0x0802E7D8
    .word @twinTiles
    .word @twinTilesEnd - @twinTiles
    .word @twinMap

.org 0x0802E828
    .word @bounce_challengeTiles
    .word @bounce_challengeTilesEnd - @bounce_challengeTiles
    .word @bounce_challengeMap

.org 0x0802E938
    .word @bounce_multiTiles
    .word @bounce_multiTilesEnd - @bounce_multiTiles
    .word @bounce_multiMap

.autoregion
    .align
    @crossfireTiles:
    .incbin "graphics\minigamesplashes\dumps\crossfireTiles.dmp" :: @crossfireTilesEnd: :: pad
    @crossfireMap:
    .incbin "graphics\minigamesplashes\dumps\crossfireMap.dmp" :: pad

    @starTiles:
    .incbin "graphics\minigamesplashes\dumps\starTiles.dmp" :: @starTilesEnd: :: pad
    @starMap:
    .incbin "graphics\minigamesplashes\dumps\starMap.dmp" :: pad

    @bounceTiles:
    .incbin "graphics\minigamesplashes\dumps\bounceTiles.dmp" :: @bounceTilesEnd: :: pad
    @bounceMap:
    .incbin "graphics\minigamesplashes\dumps\bounceMap.dmp" :: pad

    @dotsTiles:
    .incbin "graphics\minigamesplashes\dumps\dotsTiles.dmp" :: @dotsTilesEnd: :: pad
    @dotsMap:
    .incbin "graphics\minigamesplashes\dumps\dotsMap.dmp" :: pad

    @grassTiles:
    .incbin "graphics\minigamesplashes\dumps\grassTiles.dmp" :: @grassTilesEnd: :: pad
    @grassMap:
    .incbin "graphics\minigamesplashes\dumps\grassMap.dmp" :: pad

    @iceTiles:
    .incbin "graphics\minigamesplashes\dumps\iceTiles.dmp" :: @iceTilesEnd: :: pad
    @iceMap:
    .incbin "graphics\minigamesplashes\dumps\iceMap.dmp" :: pad

    @skyTiles:
    .incbin "graphics\minigamesplashes\dumps\skyTiles.dmp" :: @skyTilesEnd: :: pad
    @skyMap:
    .incbin "graphics\minigamesplashes\dumps\skyMap.dmp" :: pad

    @fallTiles:
    .incbin "graphics\minigamesplashes\dumps\fallTiles.dmp" :: @fallTilesEnd: :: pad
    @fallMap:
    .incbin "graphics\minigamesplashes\dumps\fallMap.dmp" :: pad

    @magnetTiles:
    .incbin "graphics\minigamesplashes\dumps\magnetTiles.dmp" :: @magnetTilesEnd: :: pad
    @magnetMap:
    .incbin "graphics\minigamesplashes\dumps\magnetMap.dmp" :: pad

    @raceTiles:
    .incbin "graphics\minigamesplashes\dumps\raceTiles.dmp" :: @raceTilesEnd: :: pad
    @raceMap:
    .incbin "graphics\minigamesplashes\dumps\raceMap.dmp" :: pad

    @shootTiles:
    .incbin "graphics\minigamesplashes\dumps\shootTiles.dmp" :: @shootTilesEnd: :: pad
    @shootMap:
    .incbin "graphics\minigamesplashes\dumps\shootMap.dmp" :: pad

    @twinTiles:
    .incbin "graphics\minigamesplashes\dumps\twinTiles.dmp" :: @twinTilesEnd: :: pad
    @twinMap:
    .incbin "graphics\minigamesplashes\dumps\twinMap.dmp" :: pad

    @bounce_challengeTiles:
    .incbin "graphics\minigamesplashes\dumps\bounce_challengeTiles.dmp" :: @bounce_challengeTilesEnd: :: pad
    @bounce_challengeMap:
    .incbin "graphics\minigamesplashes\dumps\bounce_challengeMap.dmp" :: pad

    @bounce_multiTiles:
    .incbin "graphics\minigamesplashes\dumps\bounce_multiTiles.dmp" :: @bounce_multiTilesEnd: :: pad
    @bounce_multiMap:
    .incbin "graphics\minigamesplashes\dumps\bounce_multiMap.dmp" :: pad
.endautoregion