; This file was automatically generated by formatsplashes.py

.org    0x082339F4
.region 0x08278D98-.,00 ; space taken by original minigame splash screens
.endregion

.macro pad
    .word 0x00 :: .align
.endmacro

; minigame splash struct array at 0x2E6D4 (16 bytes each)
; 1st dword (4 bytes) - palette pointer
; 2nd dword - tileset pointer (compressed)
; 3rd dword - compressed tileset size
; 4th dword - tilemap pointer (compressed)

; 0x02E6D4 ~ 0x02E6F4 - 2 blank entries

; 0x02E6F4 - crossfire palette would be here

.org 0x0802E6F4
    .word @crossfirePalette
    .word @crossfireTiles
    .word @crossfireTilesEnd - @crossfireTiles
    .word @crossfireMap

.org 0x0802E704
    .word @starPalette
    .word @starTiles
    .word @starTilesEnd - @starTiles
    .word @starMap

.org 0x0802E714
    .word @bouncePalette
    .word @bounceTiles
    .word @bounceTilesEnd - @bounceTiles
    .word @bounceMap

.org 0x0802E734
    .word @dotsPalette
    .word @dotsTiles
    .word @dotsTilesEnd - @dotsTiles
    .word @dotsMap

.org 0x0802E744
    .word @grassPalette
    .word @grassTiles
    .word @grassTilesEnd - @grassTiles
    .word @grassMap

.org 0x0802E754
    .word @icePalette
    .word @iceTiles
    .word @iceTilesEnd - @iceTiles
    .word @iceMap

.org 0x0802E764
    .word @skyPalette
    .word @skyTiles
    .word @skyTilesEnd - @skyTiles
    .word @skyMap

.org 0x0802E794
    .word @fallPalette
    .word @fallTiles
    .word @fallTilesEnd - @fallTiles
    .word @fallMap

.org 0x0802E7A4
    .word @magnetPalette
    .word @magnetTiles
    .word @magnetTilesEnd - @magnetTiles
    .word @magnetMap

.org 0x0802E7B4
    .word @racePalette
    .word @raceTiles
    .word @raceTilesEnd - @raceTiles
    .word @raceMap

.org 0x0802E7C4
    .word @shootPalette
    .word @shootTiles
    .word @shootTilesEnd - @shootTiles
    .word @shootMap

.org 0x0802E7D4
    .word @twinPalette
    .word @twinTiles
    .word @twinTilesEnd - @twinTiles
    .word @twinMap

.org 0x0802E7F4
    .word @chuchuPalette
    .word @chuchuTiles
    .word @chuchuTilesEnd - @chuchuTiles
    .word @chuchu_challengeMap

.org 0x0802E804
    .word @crossfirePalette
    .word @crossfire_challengeTiles
    .word @crossfire_challengeTilesEnd - @crossfire_challengeTiles
    .word @crossfire_challengeMap

.org 0x0802E814
    .word @starPalette
    .word @star_challengeTiles
    .word @star_challengeTilesEnd - @star_challengeTiles
    .word @star_challengeMap

.org 0x0802E824
    .word @bouncePalette
    .word @bounce_challengeTiles
    .word @bounce_challengeTilesEnd - @bounce_challengeTiles
    .word @bounce_challengeMap

.org 0x0802E834
    .word @hockeyPalette
    .word @hockey_challengeTiles
    .word @hockey_challengeTilesEnd - @hockey_challengeTiles
    .word @hockey_challengeMap

.org 0x0802E844
    .word @dotsPalette
    .word @dots_challengeTiles
    .word @dots_challengeTilesEnd - @dots_challengeTiles
    .word @dots_challengeMap

.org 0x0802E854
    .word @grassPalette
    .word @grass_challengeTiles
    .word @grass_challengeTilesEnd - @grass_challengeTiles
    .word @grass_challengeMap

.org 0x0802E864
    .word @icePalette
    .word @ice_challengeTiles
    .word @ice_challengeTilesEnd - @ice_challengeTiles
    .word @ice_challengeMap

.org 0x0802E874
    .word @skyPalette
    .word @sky_challengeTiles
    .word @sky_challengeTilesEnd - @sky_challengeTiles
    .word @sky_challengeMap

.org 0x0802E884
    .word @flipPalette
    .word @flip_challengeTiles
    .word @flip_challengeTilesEnd - @flip_challengeTiles
    .word @flip_challengeMap

.org 0x0802E894
    .word @lovePalette
    .word @love_challengeTiles
    .word @love_challengeTilesEnd - @love_challengeTiles
    .word @love_challengeMap

.org 0x0802E8A4
    .word @fallPalette
    .word @fall_challengeTiles
    .word @fall_challengeTilesEnd - @fall_challengeTiles
    .word @fall_challengeMap

.org 0x0802E8B4
    .word @magnetPalette
    .word @magnet_challengeTiles
    .word @magnet_challengeTilesEnd - @magnet_challengeTiles
    .word @magnet_challengeMap

.org 0x0802E8C4
    .word @racePalette
    .word @race_challengeTiles
    .word @race_challengeTilesEnd - @race_challengeTiles
    .word @race_challengeMap

.org 0x0802E8D4
    .word @shootPalette
    .word @shoot_challengeTiles
    .word @shoot_challengeTilesEnd - @shoot_challengeTiles
    .word @shoot_challengeMap

.org 0x0802E8E4
    .word @twinPalette
    .word @twin_challengeTiles
    .word @twin_challengeTilesEnd - @twin_challengeTiles
    .word @twin_challengeMap

.org 0x0802E904
    .word @chuchuPalette
    .word @chuchuTiles
    .word @chuchuTilesEnd - @chuchuTiles
    .word @chuchu_multiMap

.org 0x0802E914
    .word @crossfirePalette
    .word @crossfire_multiTiles
    .word @crossfire_multiTilesEnd - @crossfire_multiTiles
    .word @crossfire_multiMap

.org 0x0802E924
    .word @starPalette
    .word @star_multiTiles
    .word @star_multiTilesEnd - @star_multiTiles
    .word @star_multiMap

.org 0x0802E934
    .word @bouncePalette
    .word @bounce_multiTiles
    .word @bounce_multiTilesEnd - @bounce_multiTiles
    .word @bounce_multiMap

.org 0x0802E944
    .word @hockeyPalette
    .word @hockey_multiTiles
    .word @hockey_multiTilesEnd - @hockey_multiTiles
    .word @hockey_multiMap

.org 0x0802E954
    .word @dotsPalette
    .word @dots_multiTiles
    .word @dots_multiTilesEnd - @dots_multiTiles
    .word @dots_multiMap

.org 0x0802E964
    .word @grassPalette
    .word @grass_multiTiles
    .word @grass_multiTilesEnd - @grass_multiTiles
    .word @grass_multiMap

.org 0x0802E974
    .word @icePalette
    .word @ice_multiTiles
    .word @ice_multiTilesEnd - @ice_multiTiles
    .word @ice_multiMap

.org 0x0802E984
    .word @skyPalette
    .word @sky_multiTiles
    .word @sky_multiTilesEnd - @sky_multiTiles
    .word @sky_multiMap

.org 0x0802E994
    .word @flipPalette
    .word @flip_multiTiles
    .word @flip_multiTilesEnd - @flip_multiTiles
    .word @flip_multiMap

.org 0x0802E9A4
    .word @lovePalette
    .word @love_multiTiles
    .word @love_multiTilesEnd - @love_multiTiles
    .word @love_multiMap

.org 0x0802E9B4
    .word @fallPalette
    .word @fall_multiTiles
    .word @fall_multiTilesEnd - @fall_multiTiles
    .word @fall_multiMap

.org 0x0802E9C4
    .word @magnetPalette
    .word @magnet_multiTiles
    .word @magnet_multiTilesEnd - @magnet_multiTiles
    .word @magnet_multiMap

.org 0x0802E9D4
    .word @racePalette
    .word @race_multiTiles
    .word @race_multiTilesEnd - @race_multiTiles
    .word @race_multiMap

.org 0x0802E9E4
    .word @shootPalette
    .word @shoot_multiTiles
    .word @shoot_multiTilesEnd - @shoot_multiTiles
    .word @shoot_multiMap

.org 0x0802E9F4
    .word @twinPalette
    .word @twin_multiTiles
    .word @twin_multiTilesEnd - @twin_multiTiles
    .word @twin_multiMap

.autoregion :: .align   
    @crossfireTiles:
    .incbin "graphics\minigamesplashes\dumps\crossfireTiles.dmp" :: @crossfireTilesEnd: :: pad
.endautoregion

.autoregion :: .align
    @crossfireMap:
    .incbin "graphics\minigamesplashes\dumps\crossfireMap.dmp" :: pad
.endautoregion

.autoregion :: .align   
    @starTiles:
    .incbin "graphics\minigamesplashes\dumps\starTiles.dmp" :: @starTilesEnd: :: pad
.endautoregion

.autoregion :: .align
    @starMap:
    .incbin "graphics\minigamesplashes\dumps\starMap.dmp" :: pad
.endautoregion

.autoregion :: .align   
    @bounceTiles:
    .incbin "graphics\minigamesplashes\dumps\bounceTiles.dmp" :: @bounceTilesEnd: :: pad
.endautoregion

.autoregion :: .align
    @bounceMap:
    .incbin "graphics\minigamesplashes\dumps\bounceMap.dmp" :: pad
.endautoregion

.autoregion :: .align   
    @dotsTiles:
    .incbin "graphics\minigamesplashes\dumps\dotsTiles.dmp" :: @dotsTilesEnd: :: pad
.endautoregion

.autoregion :: .align
    @dotsMap:
    .incbin "graphics\minigamesplashes\dumps\dotsMap.dmp" :: pad
.endautoregion

.autoregion :: .align   
    @grassTiles:
    .incbin "graphics\minigamesplashes\dumps\grassTiles.dmp" :: @grassTilesEnd: :: pad
.endautoregion

.autoregion :: .align
    @grassMap:
    .incbin "graphics\minigamesplashes\dumps\grassMap.dmp" :: pad
.endautoregion

.autoregion :: .align   
    @iceTiles:
    .incbin "graphics\minigamesplashes\dumps\iceTiles.dmp" :: @iceTilesEnd: :: pad
.endautoregion

.autoregion :: .align
    @iceMap:
    .incbin "graphics\minigamesplashes\dumps\iceMap.dmp" :: pad
.endautoregion

.autoregion :: .align   
    @skyTiles:
    .incbin "graphics\minigamesplashes\dumps\skyTiles.dmp" :: @skyTilesEnd: :: pad
.endautoregion

.autoregion :: .align
    @skyMap:
    .incbin "graphics\minigamesplashes\dumps\skyMap.dmp" :: pad
.endautoregion

.autoregion :: .align   
    @fallTiles:
    .incbin "graphics\minigamesplashes\dumps\fallTiles.dmp" :: @fallTilesEnd: :: pad
.endautoregion

.autoregion :: .align
    @fallMap:
    .incbin "graphics\minigamesplashes\dumps\fallMap.dmp" :: pad
.endautoregion

.autoregion :: .align   
    @magnetTiles:
    .incbin "graphics\minigamesplashes\dumps\magnetTiles.dmp" :: @magnetTilesEnd: :: pad
.endautoregion

.autoregion :: .align
    @magnetMap:
    .incbin "graphics\minigamesplashes\dumps\magnetMap.dmp" :: pad
.endautoregion

.autoregion :: .align   
    @raceTiles:
    .incbin "graphics\minigamesplashes\dumps\raceTiles.dmp" :: @raceTilesEnd: :: pad
.endautoregion

.autoregion :: .align
    @raceMap:
    .incbin "graphics\minigamesplashes\dumps\raceMap.dmp" :: pad
.endautoregion

.autoregion :: .align   
    @shootTiles:
    .incbin "graphics\minigamesplashes\dumps\shootTiles.dmp" :: @shootTilesEnd: :: pad
.endautoregion

.autoregion :: .align
    @shootMap:
    .incbin "graphics\minigamesplashes\dumps\shootMap.dmp" :: pad
.endautoregion

.autoregion :: .align   
    @twinTiles:
    .incbin "graphics\minigamesplashes\dumps\twinTiles.dmp" :: @twinTilesEnd: :: pad
.endautoregion

.autoregion :: .align
    @twinMap:
    .incbin "graphics\minigamesplashes\dumps\twinMap.dmp" :: pad
.endautoregion

.autoregion :: .align   
    @chuchuTiles:
    .incbin "graphics\minigamesplashes\dumps\chuchuTiles.dmp" :: @chuchuTilesEnd: :: pad
.endautoregion

.autoregion :: .align
    @chuchu_challengeMap:
    .incbin "graphics\minigamesplashes\dumps\chuchu_challengeMap.dmp" :: pad
.endautoregion

.autoregion :: .align   
    @crossfire_challengeTiles:
    .incbin "graphics\minigamesplashes\dumps\crossfire_challengeTiles.dmp" :: @crossfire_challengeTilesEnd: :: pad
.endautoregion

.autoregion :: .align
    @crossfire_challengeMap:
    .incbin "graphics\minigamesplashes\dumps\crossfire_challengeMap.dmp" :: pad
.endautoregion

.autoregion :: .align   
    @star_challengeTiles:
    .incbin "graphics\minigamesplashes\dumps\star_challengeTiles.dmp" :: @star_challengeTilesEnd: :: pad
.endautoregion

.autoregion :: .align
    @star_challengeMap:
    .incbin "graphics\minigamesplashes\dumps\star_challengeMap.dmp" :: pad
.endautoregion

.autoregion :: .align   
    @bounce_challengeTiles:
    .incbin "graphics\minigamesplashes\dumps\bounce_challengeTiles.dmp" :: @bounce_challengeTilesEnd: :: pad
.endautoregion

.autoregion :: .align
    @bounce_challengeMap:
    .incbin "graphics\minigamesplashes\dumps\bounce_challengeMap.dmp" :: pad
.endautoregion

.autoregion :: .align   
    @hockey_challengeTiles:
    .incbin "graphics\minigamesplashes\dumps\hockey_challengeTiles.dmp" :: @hockey_challengeTilesEnd: :: pad
.endautoregion

.autoregion :: .align
    @hockey_challengeMap:
    .incbin "graphics\minigamesplashes\dumps\hockey_challengeMap.dmp" :: pad
.endautoregion

.autoregion :: .align   
    @dots_challengeTiles:
    .incbin "graphics\minigamesplashes\dumps\dots_challengeTiles.dmp" :: @dots_challengeTilesEnd: :: pad
.endautoregion

.autoregion :: .align
    @dots_challengeMap:
    .incbin "graphics\minigamesplashes\dumps\dots_challengeMap.dmp" :: pad
.endautoregion

.autoregion :: .align   
    @grass_challengeTiles:
    .incbin "graphics\minigamesplashes\dumps\grass_challengeTiles.dmp" :: @grass_challengeTilesEnd: :: pad
.endautoregion

.autoregion :: .align
    @grass_challengeMap:
    .incbin "graphics\minigamesplashes\dumps\grass_challengeMap.dmp" :: pad
.endautoregion

.autoregion :: .align   
    @ice_challengeTiles:
    .incbin "graphics\minigamesplashes\dumps\ice_challengeTiles.dmp" :: @ice_challengeTilesEnd: :: pad
.endautoregion

.autoregion :: .align
    @ice_challengeMap:
    .incbin "graphics\minigamesplashes\dumps\ice_challengeMap.dmp" :: pad
.endautoregion

.autoregion :: .align   
    @sky_challengeTiles:
    .incbin "graphics\minigamesplashes\dumps\sky_challengeTiles.dmp" :: @sky_challengeTilesEnd: :: pad
.endautoregion

.autoregion :: .align
    @sky_challengeMap:
    .incbin "graphics\minigamesplashes\dumps\sky_challengeMap.dmp" :: pad
.endautoregion

.autoregion :: .align   
    @flip_challengeTiles:
    .incbin "graphics\minigamesplashes\dumps\flip_challengeTiles.dmp" :: @flip_challengeTilesEnd: :: pad
.endautoregion

.autoregion :: .align
    @flip_challengeMap:
    .incbin "graphics\minigamesplashes\dumps\flip_challengeMap.dmp" :: pad
.endautoregion

.autoregion :: .align   
    @love_challengeTiles:
    .incbin "graphics\minigamesplashes\dumps\love_challengeTiles.dmp" :: @love_challengeTilesEnd: :: pad
.endautoregion

.autoregion :: .align
    @love_challengeMap:
    .incbin "graphics\minigamesplashes\dumps\love_challengeMap.dmp" :: pad
.endautoregion

.autoregion :: .align   
    @fall_challengeTiles:
    .incbin "graphics\minigamesplashes\dumps\fall_challengeTiles.dmp" :: @fall_challengeTilesEnd: :: pad
.endautoregion

.autoregion :: .align
    @fall_challengeMap:
    .incbin "graphics\minigamesplashes\dumps\fall_challengeMap.dmp" :: pad
.endautoregion

.autoregion :: .align   
    @magnet_challengeTiles:
    .incbin "graphics\minigamesplashes\dumps\magnet_challengeTiles.dmp" :: @magnet_challengeTilesEnd: :: pad
.endautoregion

.autoregion :: .align
    @magnet_challengeMap:
    .incbin "graphics\minigamesplashes\dumps\magnet_challengeMap.dmp" :: pad
.endautoregion

.autoregion :: .align   
    @race_challengeTiles:
    .incbin "graphics\minigamesplashes\dumps\race_challengeTiles.dmp" :: @race_challengeTilesEnd: :: pad
.endautoregion

.autoregion :: .align
    @race_challengeMap:
    .incbin "graphics\minigamesplashes\dumps\race_challengeMap.dmp" :: pad
.endautoregion

.autoregion :: .align   
    @shoot_challengeTiles:
    .incbin "graphics\minigamesplashes\dumps\shoot_challengeTiles.dmp" :: @shoot_challengeTilesEnd: :: pad
.endautoregion

.autoregion :: .align
    @shoot_challengeMap:
    .incbin "graphics\minigamesplashes\dumps\shoot_challengeMap.dmp" :: pad
.endautoregion

.autoregion :: .align   
    @twin_challengeTiles:
    .incbin "graphics\minigamesplashes\dumps\twin_challengeTiles.dmp" :: @twin_challengeTilesEnd: :: pad
.endautoregion

.autoregion :: .align
    @twin_challengeMap:
    .incbin "graphics\minigamesplashes\dumps\twin_challengeMap.dmp" :: pad
.endautoregion

.autoregion :: .align
    @chuchu_multiMap:
    .incbin "graphics\minigamesplashes\dumps\chuchu_multiMap.dmp" :: pad
.endautoregion

.autoregion :: .align
    @chuchuPalette:
    .incbin "kp.gba",0x246730,0x200
.endautoregion

.autoregion :: .align   
    @crossfire_multiTiles:
    .incbin "graphics\minigamesplashes\dumps\crossfire_multiTiles.dmp" :: @crossfire_multiTilesEnd: :: pad
.endautoregion

.autoregion :: .align
    @crossfire_multiMap:
    .incbin "graphics\minigamesplashes\dumps\crossfire_multiMap.dmp" :: pad
.endautoregion

.autoregion :: .align
    @crossfirePalette:
    .incbin "kp.gba",0x247CE4,0x200
.endautoregion

.autoregion :: .align   
    @star_multiTiles:
    .incbin "graphics\minigamesplashes\dumps\star_multiTiles.dmp" :: @star_multiTilesEnd: :: pad
.endautoregion

.autoregion :: .align
    @star_multiMap:
    .incbin "graphics\minigamesplashes\dumps\star_multiMap.dmp" :: pad
.endautoregion

.autoregion :: .align
    @starPalette:
    .incbin "kp.gba",0x24930C,0x200
.endautoregion

.autoregion :: .align   
    @bounce_multiTiles:
    .incbin "graphics\minigamesplashes\dumps\bounce_multiTiles.dmp" :: @bounce_multiTilesEnd: :: pad
.endautoregion

.autoregion :: .align
    @bounce_multiMap:
    .incbin "graphics\minigamesplashes\dumps\bounce_multiMap.dmp" :: pad
.endautoregion

.autoregion :: .align
    @bouncePalette:
    .incbin "kp.gba",0x25D3F8,0x200
.endautoregion

.autoregion :: .align   
    @hockey_multiTiles:
    .incbin "graphics\minigamesplashes\dumps\hockey_multiTiles.dmp" :: @hockey_multiTilesEnd: :: pad
.endautoregion

.autoregion :: .align
    @hockey_multiMap:
    .incbin "graphics\minigamesplashes\dumps\hockey_multiMap.dmp" :: pad
.endautoregion

.autoregion :: .align
    @hockeyPalette:
    .incbin "kp.gba",0x24AE38,0x200
.endautoregion

.autoregion :: .align   
    @dots_multiTiles:
    .incbin "graphics\minigamesplashes\dumps\dots_multiTiles.dmp" :: @dots_multiTilesEnd: :: pad
.endautoregion

.autoregion :: .align
    @dots_multiMap:
    .incbin "graphics\minigamesplashes\dumps\dots_multiMap.dmp" :: pad
.endautoregion

.autoregion :: .align
    @dotsPalette:
    .incbin "kp.gba",0x24C33C,0x200
.endautoregion

.autoregion :: .align   
    @grass_multiTiles:
    .incbin "graphics\minigamesplashes\dumps\grass_multiTiles.dmp" :: @grass_multiTilesEnd: :: pad
.endautoregion

.autoregion :: .align
    @grass_multiMap:
    .incbin "graphics\minigamesplashes\dumps\grass_multiMap.dmp" :: pad
.endautoregion

.autoregion :: .align
    @grassPalette:
    .incbin "kp.gba",0x24E1D8,0x200
.endautoregion

.autoregion :: .align   
    @ice_multiTiles:
    .incbin "graphics\minigamesplashes\dumps\ice_multiTiles.dmp" :: @ice_multiTilesEnd: :: pad
.endautoregion

.autoregion :: .align
    @ice_multiMap:
    .incbin "graphics\minigamesplashes\dumps\ice_multiMap.dmp" :: pad
.endautoregion

.autoregion :: .align
    @icePalette:
    .incbin "kp.gba",0x24FA5C,0x200
.endautoregion

.autoregion :: .align   
    @sky_multiTiles:
    .incbin "graphics\minigamesplashes\dumps\sky_multiTiles.dmp" :: @sky_multiTilesEnd: :: pad
.endautoregion

.autoregion :: .align
    @sky_multiMap:
    .incbin "graphics\minigamesplashes\dumps\sky_multiMap.dmp" :: pad
.endautoregion

.autoregion :: .align
    @skyPalette:
    .incbin "kp.gba",0x250EDC,0x200
.endautoregion

.autoregion :: .align   
    @flip_multiTiles:
    .incbin "graphics\minigamesplashes\dumps\flip_multiTiles.dmp" :: @flip_multiTilesEnd: :: pad
.endautoregion

.autoregion :: .align
    @flip_multiMap:
    .incbin "graphics\minigamesplashes\dumps\flip_multiMap.dmp" :: pad
.endautoregion

.autoregion :: .align
    @flipPalette:
    .incbin "kp.gba",0x2526A4,0x200
.endautoregion

.autoregion :: .align   
    @love_multiTiles:
    .incbin "graphics\minigamesplashes\dumps\love_multiTiles.dmp" :: @love_multiTilesEnd: :: pad
.endautoregion

.autoregion :: .align
    @love_multiMap:
    .incbin "graphics\minigamesplashes\dumps\love_multiMap.dmp" :: pad
.endautoregion

.autoregion :: .align
    @lovePalette:
    .incbin "kp.gba",0x254024,0x200
.endautoregion

.autoregion :: .align   
    @fall_multiTiles:
    .incbin "graphics\minigamesplashes\dumps\fall_multiTiles.dmp" :: @fall_multiTilesEnd: :: pad
.endautoregion

.autoregion :: .align
    @fall_multiMap:
    .incbin "graphics\minigamesplashes\dumps\fall_multiMap.dmp" :: pad
.endautoregion

.autoregion :: .align
    @fallPalette:
    .incbin "kp.gba",0x255E74,0x200
.endautoregion

.autoregion :: .align   
    @magnet_multiTiles:
    .incbin "graphics\minigamesplashes\dumps\magnet_multiTiles.dmp" :: @magnet_multiTilesEnd: :: pad
.endautoregion

.autoregion :: .align
    @magnet_multiMap:
    .incbin "graphics\minigamesplashes\dumps\magnet_multiMap.dmp" :: pad
.endautoregion

.autoregion :: .align
    @magnetPalette:
    .incbin "kp.gba",0x25795C,0x200
.endautoregion

.autoregion :: .align   
    @race_multiTiles:
    .incbin "graphics\minigamesplashes\dumps\race_multiTiles.dmp" :: @race_multiTilesEnd: :: pad
.endautoregion

.autoregion :: .align
    @race_multiMap:
    .incbin "graphics\minigamesplashes\dumps\race_multiMap.dmp" :: pad
.endautoregion

.autoregion :: .align
    @racePalette:
    .incbin "kp.gba",0x2593E8,0x200
.endautoregion

.autoregion :: .align   
    @shoot_multiTiles:
    .incbin "graphics\minigamesplashes\dumps\shoot_multiTiles.dmp" :: @shoot_multiTilesEnd: :: pad
.endautoregion

.autoregion :: .align
    @shoot_multiMap:
    .incbin "graphics\minigamesplashes\dumps\shoot_multiMap.dmp" :: pad
.endautoregion

.autoregion :: .align
    @shootPalette:
    .incbin "kp.gba",0x25A628,0x200
.endautoregion

.autoregion :: .align   
    @twin_multiTiles:
    .incbin "graphics\minigamesplashes\dumps\twin_multiTiles.dmp" :: @twin_multiTilesEnd: :: pad
.endautoregion

.autoregion :: .align
    @twin_multiMap:
    .incbin "graphics\minigamesplashes\dumps\twin_multiMap.dmp" :: pad
.endautoregion

.autoregion :: .align
    @twinPalette:
    .incbin "kp.gba",0x25BDE8,0x200
.endautoregion
