; This file was automatically generated by formatsplashes.py

.org 0x080AD254
    .word @entry_villageTiles - 0x08138C54 
    .word @entry_villageTilesEnd - @entry_villageTiles :: .skip 0x08
    .word @entry_villageMap - 0x08138C54

.org 0x080AD310
    .word @entry_flowerTiles - 0x08138C54 
    .word @entry_flowerTilesEnd - @entry_flowerTiles :: .skip 0x08
    .word @entry_flowerMap - 0x08138C54

.org 0x080AD3C8
    .word @entry_clockTiles - 0x08138C54 
    .word @entry_clockTilesEnd - @entry_clockTiles :: .skip 0x08
    .word @entry_clockMap - 0x08138C54

.org 0x080AD480
    .word @entry_magicTiles - 0x08138C54 
    .word @entry_magicTilesEnd - @entry_magicTiles :: .skip 0x08
    .word @entry_magicMap - 0x08138C54

.org 0x080AD538
    .word @entry_neoTiles - 0x08138C54 
    .word @entry_neoTilesEnd - @entry_neoTiles :: .skip 0x08
    .word @entry_neoMap - 0x08138C54

.autoregion
    .align
    @entry_villageTiles:
    .incbin "graphics\minigamesplashes\dumps\entry_villageTiles.dmp" :: @entry_villageTilesEnd: :: .align
    @entry_villageMap:
    .incbin "graphics\minigamesplashes\dumps\entry_villageMap.dmp" :: .align

    @entry_flowerTiles:
    .incbin "graphics\minigamesplashes\dumps\entry_flowerTiles.dmp" :: @entry_flowerTilesEnd: :: .align
    @entry_flowerMap:
    .incbin "graphics\minigamesplashes\dumps\entry_flowerMap.dmp" :: .align

    @entry_clockTiles:
    .incbin "graphics\minigamesplashes\dumps\entry_clockTiles.dmp" :: @entry_clockTilesEnd: :: .align
    @entry_clockMap:
    .incbin "graphics\minigamesplashes\dumps\entry_clockMap.dmp" :: .align

    @entry_magicTiles:
    .incbin "graphics\minigamesplashes\dumps\entry_magicTiles.dmp" :: @entry_magicTilesEnd: :: .align
    @entry_magicMap:
    .incbin "graphics\minigamesplashes\dumps\entry_magicMap.dmp" :: .align

    @entry_neoTiles:
    .incbin "graphics\minigamesplashes\dumps\entry_neoTiles.dmp" :: @entry_neoTilesEnd: :: .align
    @entry_neoMap:
    .incbin "graphics\minigamesplashes\dumps\entry_neoMap.dmp" :: .align
.endautoregion