; This file was automatically generated by formatsplashes.py

.org 0x0819C3A4
.region 0x081BAF44-.,00 ; space taken by original splash screens + palettes
.endregion

.org 0x080AD254
    .word @entry_villageTiles - 0x08138C54 
    .word @entry_villageTilesEnd - @entry_villageTiles :: .skip 0x08
    .word @entry_villageMap - 0x08138C54 :: .skip 0x0C
    .word @entry_villagePalette - 0x08138C54

.org 0x080AD310
    .word @entry_flowerTiles - 0x08138C54 
    .word @entry_flowerTilesEnd - @entry_flowerTiles :: .skip 0x08
    .word @entry_flowerMap - 0x08138C54 :: .skip 0x0C
    .word @entry_flowerPalette - 0x08138C54

.org 0x080AD3C8
    .word @entry_clockTiles - 0x08138C54 
    .word @entry_clockTilesEnd - @entry_clockTiles :: .skip 0x08
    .word @entry_clockMap - 0x08138C54 :: .skip 0x0C
    .word @entry_clockPalette - 0x08138C54

.org 0x080AD480
    .word @entry_magicTiles - 0x08138C54 
    .word @entry_magicTilesEnd - @entry_magicTiles :: .skip 0x08
    .word @entry_magicMap - 0x08138C54 :: .skip 0x0C
    .word @entry_magicPalette - 0x08138C54

.org 0x080AD538
    .word @entry_neoTiles - 0x08138C54 
    .word @entry_neoTilesEnd - @entry_neoTiles :: .skip 0x08
    .word @entry_neoMap - 0x08138C54 :: .skip 0x0C
    .word @entry_neoPalette - 0x08138C54

.org 0x080AD5F0
    .word @congratsTiles - 0x08138C54 
    .word @congratsTilesEnd - @congratsTiles :: .skip 0x08
    .word @congratsMap - 0x08138C54 :: .skip 0x0C
    .word @congratsPalette - 0x08138C54

.autoregion :: .align    
    @entry_villageTiles:
    .incbin "graphics\minigamesplashes\dumps\entry_villageTiles.dmp" :: @entry_villageTilesEnd: :: .align
.endautoregion

.autoregion :: .align
    @entry_villageMap:
    .incbin "graphics\minigamesplashes\dumps\entry_villageMap.dmp" :: .align
.endautoregion

.autoregion :: .align
    @entry_villagePalette:
    .incbin "kp.gba",0x1B41B4,0x200
.endautoregion

.autoregion :: .align    
    @entry_flowerTiles:
    .incbin "graphics\minigamesplashes\dumps\entry_flowerTiles.dmp" :: @entry_flowerTilesEnd: :: .align
.endautoregion

.autoregion :: .align
    @entry_flowerMap:
    .incbin "graphics\minigamesplashes\dumps\entry_flowerMap.dmp" :: .align
.endautoregion

.autoregion :: .align
    @entry_flowerPalette:
    .incbin "kp.gba",0x1B43B4,0x200
.endautoregion

.autoregion :: .align    
    @entry_clockTiles:
    .incbin "graphics\minigamesplashes\dumps\entry_clockTiles.dmp" :: @entry_clockTilesEnd: :: .align
.endautoregion

.autoregion :: .align
    @entry_clockMap:
    .incbin "graphics\minigamesplashes\dumps\entry_clockMap.dmp" :: .align
.endautoregion

.autoregion :: .align
    @entry_clockPalette:
    .incbin "kp.gba",0x1B45B4,0x200
.endautoregion

.autoregion :: .align    
    @entry_magicTiles:
    .incbin "graphics\minigamesplashes\dumps\entry_magicTiles.dmp" :: @entry_magicTilesEnd: :: .align
.endautoregion

.autoregion :: .align
    @entry_magicMap:
    .incbin "graphics\minigamesplashes\dumps\entry_magicMap.dmp" :: .align
.endautoregion

.autoregion :: .align
    @entry_magicPalette:
    .incbin "kp.gba",0x1B47B4,0x200
.endautoregion

.autoregion :: .align    
    @entry_neoTiles:
    .incbin "graphics\minigamesplashes\dumps\entry_neoTiles.dmp" :: @entry_neoTilesEnd: :: .align
.endautoregion

.autoregion :: .align
    @entry_neoMap:
    .incbin "graphics\minigamesplashes\dumps\entry_neoMap.dmp" :: .align
.endautoregion

.autoregion :: .align
    @entry_neoPalette:
    .incbin "kp.gba",0x1B49B4,0x200
.endautoregion

.autoregion :: .align    
    @congratsTiles:
    .incbin "graphics\minigamesplashes\dumps\congratsTiles.dmp" :: @congratsTilesEnd: :: .align
.endautoregion

.autoregion :: .align
    @congratsMap:
    .incbin "graphics\minigamesplashes\dumps\congratsMap.dmp" :: .align
.endautoregion

.autoregion :: .align
    @congratsPalette:
    .incbin "kp.gba",0x1BAD48,0x200
.endautoregion
