; This file was automatically generated by formatsplashes.py
; semi-automated process for now, manual edits are notated below:

.org 0x080AD6A8
    .word @titleTiles - 0x08138C54 
    .word @titleTilesEnd - @titleTiles :: .skip 0x08
    .word @titleMap - 0x08138C54

.org 0x08147BA4
.area 0x4B0
    .incbin "graphics\minigamesplashes\dumps\titleBG1MapFix.dmp"
.endarea

.autoregion 
    .align
    @titleTiles:
    .incbin "graphics\minigamesplashes\dumps\titleTiles.dmp"
    .fill 0x4000-(org() - @titleTiles)
    .incbin "graphics\minigamesplashes\dumps\titleBG1Tiles.dmp"
    @titleTilesEnd: :: .align
    
    @titleMap:
    .incbin "graphics\minigamesplashes\dumps\titleMap.dmp" :: .align
.endautoregion