; This file was auto-generated by txt.py
; Check out the reserve folder to see corresponding glyph images!
.macro universal_glyph_header
    .byte 0x01,0x60,0x08,0x08, \
          0x00,0xF9,0x22,0x04
.endmacro

.org 0x8039808 ; space character
    .word @glyph_space - 0x08284F70
.org 0x803980c
    .word @glyph_0x8141 - 0x08284F70
.org 0x8039810
    .word @glyph_0x8142 - 0x08284F70
.org 0x8039814
    .word @glyph_0x8143 - 0x08284F70
.org 0x8039818
    .word @glyph_0x8144 - 0x08284F70
.org 0x803981c
    .word @glyph_0x8145 - 0x08284F70
.org 0x8039820
    .word @glyph_0x8146 - 0x08284F70
.org 0x8039824
    .word @glyph_0x8147 - 0x08284F70
.org 0x8039828
    .word @glyph_0x8148 - 0x08284F70
.org 0x803982c
    .word @glyph_0x8149 - 0x08284F70
.org 0x8039830
    .word @glyph_0x814a - 0x08284F70
.org 0x8039834
    .word @glyph_0x814b - 0x08284F70
.org 0x8039838
    .word @glyph_0x814c - 0x08284F70
.org 0x803983c
    .word @glyph_0x814d - 0x08284F70
.org 0x8039840
    .word @glyph_0x814e - 0x08284F70
.org 0x8039844
    .word @glyph_0x814f - 0x08284F70
.org 0x8039848
    .word @glyph_0x8150 - 0x08284F70
.org 0x803984c
    .word @glyph_0x8151 - 0x08284F70
.org 0x8039850
    .word @glyph_0x8152 - 0x08284F70
.org 0x8039854
    .word @glyph_0x8153 - 0x08284F70
.org 0x8039858
    .word @glyph_0x8154 - 0x08284F70
.org 0x803985c
    .word @glyph_0x8155 - 0x08284F70
.org 0x8039860
    .word @glyph_0x8156 - 0x08284F70
.org 0x8039864
    .word @glyph_0x8157 - 0x08284F70
.org 0x8039868
    .word @glyph_0x8158 - 0x08284F70
.org 0x803986c
    .word @glyph_0x8159 - 0x08284F70
.org 0x8039870
    .word @glyph_0x815a - 0x08284F70
.org 0x8039874
    .word @glyph_0x815b - 0x08284F70
.org 0x8039878
    .word @glyph_0x815c - 0x08284F70
.org 0x803987c
    .word @glyph_0x815d - 0x08284F70
.org 0x8039880
    .word @glyph_0x815e - 0x08284F70
.org 0x8039884
    .word @glyph_0x815f - 0x08284F70
.org 0x8039888
    .word @glyph_0x8160 - 0x08284F70
.org 0x803988c
    .word @glyph_0x8161 - 0x08284F70
.org 0x8039890
    .word @glyph_0x8162 - 0x08284F70
.org 0x8039894
    .word @glyph_0x8163 - 0x08284F70
.org 0x8039898
    .word @glyph_0x8164 - 0x08284F70
.org 0x803989c
    .word @glyph_0x8165 - 0x08284F70
.org 0x80398a0
    .word @glyph_0x8166 - 0x08284F70
.org 0x80398a4
    .word @glyph_0x8167 - 0x08284F70
.org 0x80398a8
    .word @glyph_0x8168 - 0x08284F70
.org 0x80398ac
    .word @glyph_0x8169 - 0x08284F70
.org 0x80398b0
    .word @glyph_0x816a - 0x08284F70
.org 0x80398b4
    .word @glyph_0x816b - 0x08284F70
.org 0x80398b8
    .word @glyph_0x816c - 0x08284F70
.org 0x80398bc
    .word @glyph_0x816d - 0x08284F70
.org 0x80398c0
    .word @glyph_0x816e - 0x08284F70
.org 0x80398c4
    .word @glyph_0x816f - 0x08284F70
.org 0x80398c8
    .word @glyph_0x8170 - 0x08284F70
.org 0x80398cc
    .word @glyph_0x8171 - 0x08284F70
.org 0x80398d0
    .word @glyph_0x8172 - 0x08284F70
.org 0x80398d4
    .word @glyph_0x8173 - 0x08284F70
.org 0x80398d8
    .word @glyph_0x8174 - 0x08284F70
.org 0x80398dc
    .word @glyph_0x8175 - 0x08284F70
.org 0x80398e0
    .word @glyph_0x8176 - 0x08284F70
.org 0x80398e4
    .word @glyph_0x8177 - 0x08284F70
.org 0x80398e8
    .word @glyph_0x8178 - 0x08284F70
.org 0x80398ec
    .word @glyph_0x8179 - 0x08284F70
.org 0x80398f0
    .word @glyph_0x817a - 0x08284F70
.org 0x80398f4
    .word @glyph_0x817b - 0x08284F70
.org 0x80398f8
    .word @glyph_0x817c - 0x08284F70
.org 0x80398fc
    .word @glyph_0x817d - 0x08284F70
.org 0x8039900
    .word @glyph_0x817e - 0x08284F70
.org 0x8039908
    .word @glyph_0x8180 - 0x08284F70
.org 0x803990c
    .word @glyph_0x8181 - 0x08284F70
.org 0x8039910
    .word @glyph_0x8182 - 0x08284F70
.org 0x8039914
    .word @glyph_0x8183 - 0x08284F70
.org 0x8039918
    .word @glyph_0x8184 - 0x08284F70
.org 0x803991c
    .word @glyph_0x8185 - 0x08284F70
.org 0x8039920
    .word @glyph_0x8186 - 0x08284F70
.org 0x8039924
    .word @glyph_0x8187 - 0x08284F70
.org 0x8039928
    .word @glyph_0x8188 - 0x08284F70
.org 0x803992c
    .word @glyph_0x8189 - 0x08284F70
.org 0x8039930
    .word @glyph_0x818a - 0x08284F70
.org 0x8039934
    .word @glyph_0x818b - 0x08284F70
.org 0x8039938
    .word @glyph_0x818c - 0x08284F70
.org 0x803993c
    .word @glyph_0x818d - 0x08284F70
.org 0x8039940
    .word @glyph_0x818e - 0x08284F70
.org 0x8039944
    .word @glyph_0x818f - 0x08284F70
.org 0x8039948
    .word @glyph_0x8190 - 0x08284F70
.org 0x803994c
    .word @glyph_0x8191 - 0x08284F70
.org 0x8039950
    .word @glyph_0x8192 - 0x08284F70
.org 0x8039954
    .word @glyph_0x8193 - 0x08284F70
.org 0x8039958
    .word @glyph_0x8194 - 0x08284F70
.org 0x803995c
    .word @glyph_0x8195 - 0x08284F70
.org 0x8039960
    .word @glyph_0x8196 - 0x08284F70
.org 0x8039964
    .word @glyph_0x8197 - 0x08284F70
.org 0x8039968
    .word @glyph_0x8198 - 0x08284F70
.org 0x803996c
    .word @glyph_0x8199 - 0x08284F70
.org 0x8039970
    .word @glyph_0x819a - 0x08284F70
.org 0x8039974
    .word @glyph_0x819b - 0x08284F70
.org 0x8039978
    .word @glyph_0x819c - 0x08284F70
.org 0x803997c
    .word @glyph_0x819d - 0x08284F70
.org 0x8039980
    .word @glyph_0x819e - 0x08284F70
.org 0x8039984
    .word @glyph_0x819f - 0x08284F70
.org 0x8039988
    .word @glyph_0x81a0 - 0x08284F70
.org 0x803998c
    .word @glyph_0x81a1 - 0x08284F70
.org 0x8039990
    .word @glyph_0x81a2 - 0x08284F70
.org 0x8039994
    .word @glyph_0x81a3 - 0x08284F70
.org 0x8039998
    .word @glyph_0x81a4 - 0x08284F70
.org 0x803999c
    .word @glyph_0x81a5 - 0x08284F70
.org 0x80399a0
    .word @glyph_0x81a6 - 0x08284F70
.org 0x80399a4
    .word @glyph_0x81a7 - 0x08284F70
.org 0x80399a8
    .word @glyph_0x81a8 - 0x08284F70
.org 0x80399ac
    .word @glyph_0x81a9 - 0x08284F70
.org 0x80399b0
    .word @glyph_0x81aa - 0x08284F70
.org 0x80399b4
    .word @glyph_0x81ab - 0x08284F70
.org 0x80399b8
    .word @glyph_0x81ac - 0x08284F70
.org 0x80399e8
    .word @glyph_0x81b8 - 0x08284F70
.org 0x80399ec
    .word @glyph_0x81b9 - 0x08284F70
.org 0x80399f0
    .word @glyph_0x81ba - 0x08284F70
.org 0x80399f4
    .word @glyph_0x81bb - 0x08284F70
.org 0x80399f8
    .word @glyph_0x81bc - 0x08284F70
.org 0x80399fc
    .word @glyph_0x81bd - 0x08284F70
.org 0x8039a00
    .word @glyph_0x81be - 0x08284F70
.org 0x8039a04
    .word @glyph_0x81bf - 0x08284F70
.org 0x8039a28
    .word @glyph_0x81c8 - 0x08284F70
.org 0x8039a2c
    .word @glyph_0x81c9 - 0x08284F70
.org 0x8039a30
    .word @glyph_0x81ca - 0x08284F70
.org 0x8039a34
    .word @glyph_0x81cb - 0x08284F70
.org 0x8039a38
    .word @glyph_0x81cc - 0x08284F70
.org 0x8039a3c
    .word @glyph_0x81cd - 0x08284F70
.org 0x8039a40
    .word @glyph_0x81ce - 0x08284F70
.org 0x8039a70
    .word @glyph_0x81da - 0x08284F70
.org 0x8039a74
    .word @glyph_0x81db - 0x08284F70
.org 0x8039a78
    .word @glyph_0x81dc - 0x08284F70
.org 0x8039a7c
    .word @glyph_0x81dd - 0x08284F70
.org 0x8039a80
    .word @glyph_0x81de - 0x08284F70
.org 0x8039a84
    .word @glyph_0x81df - 0x08284F70
.org 0x8039a88
    .word @glyph_0x81e0 - 0x08284F70
.org 0x8039a8c
    .word @glyph_0x81e1 - 0x08284F70
.org 0x8039a90
    .word @glyph_0x81e2 - 0x08284F70
.org 0x8039a94
    .word @glyph_0x81e3 - 0x08284F70
.org 0x8039a98
    .word @glyph_0x81e4 - 0x08284F70
.org 0x8039a9c
    .word @glyph_0x81e5 - 0x08284F70
.org 0x8039aa0
    .word @glyph_0x81e6 - 0x08284F70
.org 0x8039aa4
    .word @glyph_0x81e7 - 0x08284F70
.org 0x8039aa8
    .word @glyph_0x81e8 - 0x08284F70
.org 0x8039ac8
    .word @glyph_0x81f0 - 0x08284F70
.org 0x8039acc
    .word @glyph_0x81f1 - 0x08284F70
.org 0x8039ad0
    .word @glyph_0x81f2 - 0x08284F70
.org 0x8039ad4
    .word @glyph_0x81f3 - 0x08284F70
.org 0x8039ad8
    .word @glyph_0x81f4 - 0x08284F70
.org 0x8039adc
    .word @glyph_0x81f5 - 0x08284F70
.org 0x8039ae0
    .word @glyph_0x81f6 - 0x08284F70
.org 0x8039ae4
    .word @glyph_0x81f7 - 0x08284F70
.org 0x8039af8
    .word @glyph_0x81fc - 0x08284F70
.org 0x8039b44
    .word @glyph_0x824f - 0x08284F70
.org 0x8039b48
    .word @glyph_0x8250 - 0x08284F70
.org 0x8039b4c
    .word @glyph_0x8251 - 0x08284F70
.org 0x8039b50
    .word @glyph_0x8252 - 0x08284F70
.org 0x8039b54
    .word @glyph_0x8253 - 0x08284F70
.org 0x8039b58
    .word @glyph_0x8254 - 0x08284F70
.org 0x8039b5c
    .word @glyph_0x8255 - 0x08284F70
.org 0x8039b60
    .word @glyph_0x8256 - 0x08284F70
.org 0x8039b64
    .word @glyph_0x8257 - 0x08284F70
.org 0x8039b68
    .word @glyph_0x8258 - 0x08284F70
.org 0x8039b88
    .word @glyph_0x8260 - 0x08284F70
.org 0x8039b8c
    .word @glyph_0x8261 - 0x08284F70
.org 0x8039b90
    .word @glyph_0x8262 - 0x08284F70
.org 0x8039b94
    .word @glyph_0x8263 - 0x08284F70
.org 0x8039b98
    .word @glyph_0x8264 - 0x08284F70
.org 0x8039b9c
    .word @glyph_0x8265 - 0x08284F70
.org 0x8039ba0
    .word @glyph_0x8266 - 0x08284F70
.org 0x8039ba4
    .word @glyph_0x8267 - 0x08284F70
.org 0x8039ba8
    .word @glyph_0x8268 - 0x08284F70
.org 0x8039bac
    .word @glyph_0x8269 - 0x08284F70
.org 0x8039bb0
    .word @glyph_0x826a - 0x08284F70
.org 0x8039bb4
    .word @glyph_0x826b - 0x08284F70
.org 0x8039bb8
    .word @glyph_0x826c - 0x08284F70
.org 0x8039bbc
    .word @glyph_0x826d - 0x08284F70
.org 0x8039bc0
    .word @glyph_0x826e - 0x08284F70
.org 0x8039bc4
    .word @glyph_0x826f - 0x08284F70
.org 0x8039bc8
    .word @glyph_0x8270 - 0x08284F70
.org 0x8039bcc
    .word @glyph_0x8271 - 0x08284F70
.org 0x8039bd0
    .word @glyph_0x8272 - 0x08284F70
.org 0x8039bd4
    .word @glyph_0x8273 - 0x08284F70
.org 0x8039bd8
    .word @glyph_0x8274 - 0x08284F70
.org 0x8039bdc
    .word @glyph_0x8275 - 0x08284F70
.org 0x8039be0
    .word @glyph_0x8276 - 0x08284F70
.org 0x8039be4
    .word @glyph_0x8277 - 0x08284F70
.org 0x8039be8
    .word @glyph_0x8278 - 0x08284F70
.org 0x8039bec
    .word @glyph_0x8279 - 0x08284F70
.org 0x8039c0c
    .word @glyph_0x8281 - 0x08284F70
.org 0x8039c10
    .word @glyph_0x8282 - 0x08284F70
.org 0x8039c14
    .word @glyph_0x8283 - 0x08284F70
.org 0x8039c18
    .word @glyph_0x8284 - 0x08284F70
.org 0x8039c1c
    .word @glyph_0x8285 - 0x08284F70
.org 0x8039c20
    .word @glyph_0x8286 - 0x08284F70
.org 0x8039c24
    .word @glyph_0x8287 - 0x08284F70
.org 0x8039c28
    .word @glyph_0x8288 - 0x08284F70
.org 0x8039c2c
    .word @glyph_0x8289 - 0x08284F70
.org 0x8039c30
    .word @glyph_0x828a - 0x08284F70
.org 0x8039c34
    .word @glyph_0x828b - 0x08284F70
.org 0x8039c38
    .word @glyph_0x828c - 0x08284F70
.org 0x8039c3c
    .word @glyph_0x828d - 0x08284F70
.org 0x8039c40
    .word @glyph_0x828e - 0x08284F70
.org 0x8039c44
    .word @glyph_0x828f - 0x08284F70
.org 0x8039c48
    .word @glyph_0x8290 - 0x08284F70
.org 0x8039c4c
    .word @glyph_0x8291 - 0x08284F70
.org 0x8039c50
    .word @glyph_0x8292 - 0x08284F70
.org 0x8039c54
    .word @glyph_0x8293 - 0x08284F70
.org 0x8039c58
    .word @glyph_0x8294 - 0x08284F70
.org 0x8039c5c
    .word @glyph_0x8295 - 0x08284F70
.org 0x8039c60
    .word @glyph_0x8296 - 0x08284F70
.org 0x8039c64
    .word @glyph_0x8297 - 0x08284F70
.org 0x8039c68
    .word @glyph_0x8298 - 0x08284F70
.org 0x8039c6c
    .word @glyph_0x8299 - 0x08284F70
.org 0x8039c70
    .word @glyph_0x829a - 0x08284F70
.org 0x8039f88
    .word @glyph_0x8740 - 0x08284F70
.org 0x8039f8c
    .word @glyph_0x8741 - 0x08284F70
.org 0x8039f90
    .word @glyph_0x8742 - 0x08284F70
.org 0x8039f94
    .word @glyph_0x8743 - 0x08284F70
.org 0x8039f98
    .word @glyph_0x8744 - 0x08284F70
.org 0x8039f9c
    .word @glyph_0x8745 - 0x08284F70
.org 0x8039fa0
    .word @glyph_0x8746 - 0x08284F70
.org 0x8039fa4
    .word @glyph_0x8747 - 0x08284F70
.org 0x8039fa8
    .word @glyph_0x8748 - 0x08284F70
.org 0x8039fac
    .word @glyph_0x8749 - 0x08284F70
.org 0x8039fb0
    .word @glyph_0x874a - 0x08284F70

.org 0x082E4EB4
.region 0x082FB354 - .
    @glyph_space:
        .byte 0x00,0x70,0x08,0x08,0x01,0x60,0x08,0x08
    .fill 0x80
    @glyph_0x8141:
    universal_glyph_header
        .incbin "graphics\glyphs\dumps\0x8141.img.bin"
    @glyph_0x8142:
    universal_glyph_header
        .incbin "graphics\glyphs\dumps\0x8142.img.bin"
    @glyph_0x8143:
    universal_glyph_header
        .incbin "graphics\glyphs\dumps\0x8143.img.bin"
    @glyph_0x8144:
    universal_glyph_header
        .incbin "graphics\glyphs\dumps\0x8144.img.bin"
    @glyph_0x8145:
    universal_glyph_header
        .incbin "graphics\glyphs\dumps\0x8145.img.bin"
    @glyph_0x8146:
    universal_glyph_header
        .incbin "graphics\glyphs\dumps\0x8146.img.bin"
    @glyph_0x8147:
    universal_glyph_header
        .incbin "graphics\glyphs\dumps\0x8147.img.bin"
    @glyph_0x8148:
    universal_glyph_header
        .incbin "graphics\glyphs\dumps\0x8148.img.bin"
    @glyph_0x8149:
    universal_glyph_header
        .incbin "graphics\glyphs\dumps\0x8149.img.bin"
    @glyph_0x814a:
    universal_glyph_header
        .incbin "graphics\glyphs\dumps\0x814a.img.bin"
    @glyph_0x814b:
    universal_glyph_header
        .incbin "graphics\glyphs\dumps\0x814b.img.bin"
    @glyph_0x814c:
    universal_glyph_header
        .incbin "graphics\glyphs\dumps\0x814c.img.bin"
    @glyph_0x814d:
    universal_glyph_header
        .incbin "graphics\glyphs\dumps\0x814d.img.bin"
    @glyph_0x814e:
    universal_glyph_header
        .incbin "graphics\glyphs\dumps\0x814e.img.bin"
    @glyph_0x814f:
    universal_glyph_header
        .incbin "graphics\glyphs\dumps\0x814f.img.bin"
    @glyph_0x8150:
    universal_glyph_header
        .incbin "graphics\glyphs\dumps\0x8150.img.bin"
    @glyph_0x8151:
    universal_glyph_header
        .incbin "graphics\glyphs\dumps\0x8151.img.bin"
    @glyph_0x8152:
    universal_glyph_header
        .incbin "graphics\glyphs\dumps\0x8152.img.bin"
    @glyph_0x8153:
    universal_glyph_header
        .incbin "graphics\glyphs\dumps\0x8153.img.bin"
    @glyph_0x8154:
    universal_glyph_header
        .incbin "graphics\glyphs\dumps\0x8154.img.bin"
    @glyph_0x8155:
    universal_glyph_header
        .incbin "graphics\glyphs\dumps\0x8155.img.bin"
    @glyph_0x8156:
    universal_glyph_header
        .incbin "graphics\glyphs\dumps\0x8156.img.bin"
    @glyph_0x8157:
    universal_glyph_header
        .incbin "graphics\glyphs\dumps\0x8157.img.bin"
    @glyph_0x8158:
    universal_glyph_header
        .incbin "graphics\glyphs\dumps\0x8158.img.bin"
    @glyph_0x8159:
    universal_glyph_header
        .incbin "graphics\glyphs\dumps\0x8159.img.bin"
    @glyph_0x815a:
    universal_glyph_header
        .incbin "graphics\glyphs\dumps\0x815a.img.bin"
    @glyph_0x815b:
    universal_glyph_header
        .incbin "graphics\glyphs\dumps\0x815b.img.bin"
    @glyph_0x815c:
    universal_glyph_header
        .incbin "graphics\glyphs\dumps\0x815c.img.bin"
    @glyph_0x815d:
    universal_glyph_header
        .incbin "graphics\glyphs\dumps\0x815d.img.bin"
    @glyph_0x815e:
    universal_glyph_header
        .incbin "graphics\glyphs\dumps\0x815e.img.bin"
    @glyph_0x815f:
    universal_glyph_header
        .incbin "graphics\glyphs\dumps\0x815f.img.bin"
    @glyph_0x8160:
    universal_glyph_header
        .incbin "graphics\glyphs\dumps\0x8160.img.bin"
    @glyph_0x8161:
    universal_glyph_header
        .incbin "graphics\glyphs\dumps\0x8161.img.bin"
    @glyph_0x8162:
    universal_glyph_header
        .incbin "graphics\glyphs\dumps\0x8162.img.bin"
    @glyph_0x8163:
    universal_glyph_header
        .incbin "graphics\glyphs\dumps\0x8163.img.bin"
    @glyph_0x8164:
    universal_glyph_header
        .incbin "graphics\glyphs\dumps\0x8164.img.bin"
    @glyph_0x8165:
    universal_glyph_header
        .incbin "graphics\glyphs\dumps\0x8165.img.bin"
    @glyph_0x8166:
    universal_glyph_header
        .incbin "graphics\glyphs\dumps\0x8166.img.bin"
    @glyph_0x8167:
    universal_glyph_header
        .incbin "graphics\glyphs\dumps\0x8167.img.bin"
    @glyph_0x8168:
    universal_glyph_header
        .incbin "graphics\glyphs\dumps\0x8168.img.bin"
    @glyph_0x8169:
    universal_glyph_header
        .incbin "graphics\glyphs\dumps\0x8169.img.bin"
    @glyph_0x816a:
    universal_glyph_header
        .incbin "graphics\glyphs\dumps\0x816a.img.bin"
    @glyph_0x816b:
    universal_glyph_header
        .incbin "graphics\glyphs\dumps\0x816b.img.bin"
    @glyph_0x816c:
    universal_glyph_header
        .incbin "graphics\glyphs\dumps\0x816c.img.bin"
    @glyph_0x816d:
    universal_glyph_header
        .incbin "graphics\glyphs\dumps\0x816d.img.bin"
    @glyph_0x816e:
    universal_glyph_header
        .incbin "graphics\glyphs\dumps\0x816e.img.bin"
    @glyph_0x816f:
    universal_glyph_header
        .incbin "graphics\glyphs\dumps\0x816f.img.bin"
    @glyph_0x8170:
    universal_glyph_header
        .incbin "graphics\glyphs\dumps\0x8170.img.bin"
    @glyph_0x8171:
    universal_glyph_header
        .incbin "graphics\glyphs\dumps\0x8171.img.bin"
    @glyph_0x8172:
    universal_glyph_header
        .incbin "graphics\glyphs\dumps\0x8172.img.bin"
    @glyph_0x8173:
    universal_glyph_header
        .incbin "graphics\glyphs\dumps\0x8173.img.bin"
    @glyph_0x8174:
    universal_glyph_header
        .incbin "graphics\glyphs\dumps\0x8174.img.bin"
    @glyph_0x8175:
    universal_glyph_header
        .incbin "graphics\glyphs\dumps\0x8175.img.bin"
    @glyph_0x8176:
    universal_glyph_header
        .incbin "graphics\glyphs\dumps\0x8176.img.bin"
    @glyph_0x8177:
    universal_glyph_header
        .incbin "graphics\glyphs\dumps\0x8177.img.bin"
    @glyph_0x8178:
    universal_glyph_header
        .incbin "graphics\glyphs\dumps\0x8178.img.bin"
    @glyph_0x8179:
    universal_glyph_header
        .incbin "graphics\glyphs\dumps\0x8179.img.bin"
    @glyph_0x817a:
    universal_glyph_header
        .incbin "graphics\glyphs\dumps\0x817a.img.bin"
    @glyph_0x817b:
    universal_glyph_header
        .incbin "graphics\glyphs\dumps\0x817b.img.bin"
    @glyph_0x817c:
    universal_glyph_header
        .incbin "graphics\glyphs\dumps\0x817c.img.bin"
    @glyph_0x817d:
    universal_glyph_header
        .incbin "graphics\glyphs\dumps\0x817d.img.bin"
    @glyph_0x817e:
    universal_glyph_header
        .incbin "graphics\glyphs\dumps\0x817e.img.bin"
    @glyph_0x8180:
    universal_glyph_header
        .incbin "graphics\glyphs\dumps\0x8180.img.bin"
    @glyph_0x8181:
    universal_glyph_header
        .incbin "graphics\glyphs\dumps\0x8181.img.bin"
    @glyph_0x8182:
    universal_glyph_header
        .incbin "graphics\glyphs\dumps\0x8182.img.bin"
    @glyph_0x8183:
    universal_glyph_header
        .incbin "graphics\glyphs\dumps\0x8183.img.bin"
    @glyph_0x8184:
    universal_glyph_header
        .incbin "graphics\glyphs\dumps\0x8184.img.bin"
    @glyph_0x8185:
    universal_glyph_header
        .incbin "graphics\glyphs\dumps\0x8185.img.bin"
    @glyph_0x8186:
    universal_glyph_header
        .incbin "graphics\glyphs\dumps\0x8186.img.bin"
    @glyph_0x8187:
    universal_glyph_header
        .incbin "graphics\glyphs\dumps\0x8187.img.bin"
    @glyph_0x8188:
    universal_glyph_header
        .incbin "graphics\glyphs\dumps\0x8188.img.bin"
    @glyph_0x8189:
    universal_glyph_header
        .incbin "graphics\glyphs\dumps\0x8189.img.bin"
    @glyph_0x818a:
    universal_glyph_header
        .incbin "graphics\glyphs\dumps\0x818a.img.bin"
    @glyph_0x818b:
    universal_glyph_header
        .incbin "graphics\glyphs\dumps\0x818b.img.bin"
    @glyph_0x818c:
    universal_glyph_header
        .incbin "graphics\glyphs\dumps\0x818c.img.bin"
    @glyph_0x818d:
    universal_glyph_header
        .incbin "graphics\glyphs\dumps\0x818d.img.bin"
    @glyph_0x818e:
    universal_glyph_header
        .incbin "graphics\glyphs\dumps\0x818e.img.bin"
    @glyph_0x818f:
    universal_glyph_header
        .incbin "graphics\glyphs\dumps\0x818f.img.bin"
    @glyph_0x8190:
    universal_glyph_header
        .incbin "graphics\glyphs\dumps\0x8190.img.bin"
    @glyph_0x8191:
    universal_glyph_header
        .incbin "graphics\glyphs\dumps\0x8191.img.bin"
    @glyph_0x8192:
    universal_glyph_header
        .incbin "graphics\glyphs\dumps\0x8192.img.bin"
    @glyph_0x8193:
    universal_glyph_header
        .incbin "graphics\glyphs\dumps\0x8193.img.bin"
    @glyph_0x8194:
    universal_glyph_header
        .incbin "graphics\glyphs\dumps\0x8194.img.bin"
    @glyph_0x8195:
    universal_glyph_header
        .incbin "graphics\glyphs\dumps\0x8195.img.bin"
    @glyph_0x8196:
    universal_glyph_header
        .incbin "graphics\glyphs\dumps\0x8196.img.bin"
    @glyph_0x8197:
    universal_glyph_header
        .incbin "graphics\glyphs\dumps\0x8197.img.bin"
    @glyph_0x8198:
    universal_glyph_header
        .incbin "graphics\glyphs\dumps\0x8198.img.bin"
    @glyph_0x8199:
    universal_glyph_header
        .incbin "graphics\glyphs\dumps\0x8199.img.bin"
    @glyph_0x819a:
    universal_glyph_header
        .incbin "graphics\glyphs\dumps\0x819a.img.bin"
    @glyph_0x819b:
    universal_glyph_header
        .incbin "graphics\glyphs\dumps\0x819b.img.bin"
    @glyph_0x819c:
    universal_glyph_header
        .incbin "graphics\glyphs\dumps\0x819c.img.bin"
    @glyph_0x819d:
    universal_glyph_header
        .incbin "graphics\glyphs\dumps\0x819d.img.bin"
    @glyph_0x819e:
    universal_glyph_header
        .incbin "graphics\glyphs\dumps\0x819e.img.bin"
    @glyph_0x819f:
    universal_glyph_header
        .incbin "graphics\glyphs\dumps\0x819f.img.bin"
    @glyph_0x81a0:
    universal_glyph_header
        .incbin "graphics\glyphs\dumps\0x81a0.img.bin"
    @glyph_0x81a1:
    universal_glyph_header
        .incbin "graphics\glyphs\dumps\0x81a1.img.bin"
    @glyph_0x81a2:
    universal_glyph_header
        .incbin "graphics\glyphs\dumps\0x81a2.img.bin"
    @glyph_0x81a3:
    universal_glyph_header
        .incbin "graphics\glyphs\dumps\0x81a3.img.bin"
    @glyph_0x81a4:
    universal_glyph_header
        .incbin "graphics\glyphs\dumps\0x81a4.img.bin"
    @glyph_0x81a5:
    universal_glyph_header
        .incbin "graphics\glyphs\dumps\0x81a5.img.bin"
    @glyph_0x81a6:
    universal_glyph_header
        .incbin "graphics\glyphs\dumps\0x81a6.img.bin"
    @glyph_0x81a7:
    universal_glyph_header
        .incbin "graphics\glyphs\dumps\0x81a7.img.bin"
    @glyph_0x81a8:
    universal_glyph_header
        .incbin "graphics\glyphs\dumps\0x81a8.img.bin"
    @glyph_0x81a9:
    universal_glyph_header
        .incbin "graphics\glyphs\dumps\0x81a9.img.bin"
    @glyph_0x81aa:
    universal_glyph_header
        .incbin "graphics\glyphs\dumps\0x81aa.img.bin"
    @glyph_0x81ab:
    universal_glyph_header
        .incbin "graphics\glyphs\dumps\0x81ab.img.bin"
    @glyph_0x81ac:
    universal_glyph_header
        .incbin "graphics\glyphs\dumps\0x81ac.img.bin"
    @glyph_0x81b8:
    universal_glyph_header
        .incbin "graphics\glyphs\dumps\0x81b8.img.bin"
    @glyph_0x81b9:
    universal_glyph_header
        .incbin "graphics\glyphs\dumps\0x81b9.img.bin"
    @glyph_0x81ba:
    universal_glyph_header
        .incbin "graphics\glyphs\dumps\0x81ba.img.bin"
    @glyph_0x81bb:
    universal_glyph_header
        .incbin "graphics\glyphs\dumps\0x81bb.img.bin"
    @glyph_0x81bc:
    universal_glyph_header
        .incbin "graphics\glyphs\dumps\0x81bc.img.bin"
    @glyph_0x81bd:
    universal_glyph_header
        .incbin "graphics\glyphs\dumps\0x81bd.img.bin"
    @glyph_0x81be:
    universal_glyph_header
        .incbin "graphics\glyphs\dumps\0x81be.img.bin"
    @glyph_0x81bf:
    universal_glyph_header
        .incbin "graphics\glyphs\dumps\0x81bf.img.bin"
    @glyph_0x81c8:
    universal_glyph_header
        .incbin "graphics\glyphs\dumps\0x81c8.img.bin"
    @glyph_0x81c9:
    universal_glyph_header
        .incbin "graphics\glyphs\dumps\0x81c9.img.bin"
    @glyph_0x81ca:
    universal_glyph_header
        .incbin "graphics\glyphs\dumps\0x81ca.img.bin"
    @glyph_0x81cb:
    universal_glyph_header
        .incbin "graphics\glyphs\dumps\0x81cb.img.bin"
    @glyph_0x81cc:
    universal_glyph_header
        .incbin "graphics\glyphs\dumps\0x81cc.img.bin"
    @glyph_0x81cd:
    universal_glyph_header
        .incbin "graphics\glyphs\dumps\0x81cd.img.bin"
    @glyph_0x81ce:
    universal_glyph_header
        .incbin "graphics\glyphs\dumps\0x81ce.img.bin"
    @glyph_0x81da:
    universal_glyph_header
        .incbin "graphics\glyphs\dumps\0x81da.img.bin"
    @glyph_0x81db:
    universal_glyph_header
        .incbin "graphics\glyphs\dumps\0x81db.img.bin"
    @glyph_0x81dc:
    universal_glyph_header
        .incbin "graphics\glyphs\dumps\0x81dc.img.bin"
    @glyph_0x81dd:
    universal_glyph_header
        .incbin "graphics\glyphs\dumps\0x81dd.img.bin"
    @glyph_0x81de:
    universal_glyph_header
        .incbin "graphics\glyphs\dumps\0x81de.img.bin"
    @glyph_0x81df:
    universal_glyph_header
        .incbin "graphics\glyphs\dumps\0x81df.img.bin"
    @glyph_0x81e0:
    universal_glyph_header
        .incbin "graphics\glyphs\dumps\0x81e0.img.bin"
    @glyph_0x81e1:
    universal_glyph_header
        .incbin "graphics\glyphs\dumps\0x81e1.img.bin"
    @glyph_0x81e2:
    universal_glyph_header
        .incbin "graphics\glyphs\dumps\0x81e2.img.bin"
    @glyph_0x81e3:
    universal_glyph_header
        .incbin "graphics\glyphs\dumps\0x81e3.img.bin"
    @glyph_0x81e4:
    universal_glyph_header
        .incbin "graphics\glyphs\dumps\0x81e4.img.bin"
    @glyph_0x81e5:
    universal_glyph_header
        .incbin "graphics\glyphs\dumps\0x81e5.img.bin"
    @glyph_0x81e6:
    universal_glyph_header
        .incbin "graphics\glyphs\dumps\0x81e6.img.bin"
    @glyph_0x81e7:
    universal_glyph_header
        .incbin "graphics\glyphs\dumps\0x81e7.img.bin"
    @glyph_0x81e8:
    universal_glyph_header
        .incbin "graphics\glyphs\dumps\0x81e8.img.bin"
    @glyph_0x81f0:
    universal_glyph_header
        .incbin "graphics\glyphs\dumps\0x81f0.img.bin"
    @glyph_0x81f1:
    universal_glyph_header
        .incbin "graphics\glyphs\dumps\0x81f1.img.bin"
    @glyph_0x81f2:
    universal_glyph_header
        .incbin "graphics\glyphs\dumps\0x81f2.img.bin"
    @glyph_0x81f3:
    universal_glyph_header
        .incbin "graphics\glyphs\dumps\0x81f3.img.bin"
    @glyph_0x81f4:
    universal_glyph_header
        .incbin "graphics\glyphs\dumps\0x81f4.img.bin"
    @glyph_0x81f5:
    universal_glyph_header
        .incbin "graphics\glyphs\dumps\0x81f5.img.bin"
    @glyph_0x81f6:
    universal_glyph_header
        .incbin "graphics\glyphs\dumps\0x81f6.img.bin"
    @glyph_0x81f7:
    universal_glyph_header
        .incbin "graphics\glyphs\dumps\0x81f7.img.bin"
    @glyph_0x81fc:
    universal_glyph_header
        .incbin "graphics\glyphs\dumps\0x81fc.img.bin"
    @glyph_0x824f:
    universal_glyph_header
        .incbin "graphics\glyphs\dumps\0x824f.img.bin"
    @glyph_0x8250:
    universal_glyph_header
        .incbin "graphics\glyphs\dumps\0x8250.img.bin"
    @glyph_0x8251:
    universal_glyph_header
        .incbin "graphics\glyphs\dumps\0x8251.img.bin"
    @glyph_0x8252:
    universal_glyph_header
        .incbin "graphics\glyphs\dumps\0x8252.img.bin"
    @glyph_0x8253:
    universal_glyph_header
        .incbin "graphics\glyphs\dumps\0x8253.img.bin"
    @glyph_0x8254:
    universal_glyph_header
        .incbin "graphics\glyphs\dumps\0x8254.img.bin"
    @glyph_0x8255:
    universal_glyph_header
        .incbin "graphics\glyphs\dumps\0x8255.img.bin"
    @glyph_0x8256:
    universal_glyph_header
        .incbin "graphics\glyphs\dumps\0x8256.img.bin"
    @glyph_0x8257:
    universal_glyph_header
        .incbin "graphics\glyphs\dumps\0x8257.img.bin"
    @glyph_0x8258:
    universal_glyph_header
        .incbin "graphics\glyphs\dumps\0x8258.img.bin"
    @glyph_0x8260:
    universal_glyph_header
        .incbin "graphics\glyphs\dumps\0x8260.img.bin"
    @glyph_0x8261:
    universal_glyph_header
        .incbin "graphics\glyphs\dumps\0x8261.img.bin"
    @glyph_0x8262:
    universal_glyph_header
        .incbin "graphics\glyphs\dumps\0x8262.img.bin"
    @glyph_0x8263:
    universal_glyph_header
        .incbin "graphics\glyphs\dumps\0x8263.img.bin"
    @glyph_0x8264:
    universal_glyph_header
        .incbin "graphics\glyphs\dumps\0x8264.img.bin"
    @glyph_0x8265:
    universal_glyph_header
        .incbin "graphics\glyphs\dumps\0x8265.img.bin"
    @glyph_0x8266:
    universal_glyph_header
        .incbin "graphics\glyphs\dumps\0x8266.img.bin"
    @glyph_0x8267:
    universal_glyph_header
        .incbin "graphics\glyphs\dumps\0x8267.img.bin"
    @glyph_0x8268:
    universal_glyph_header
        .incbin "graphics\glyphs\dumps\0x8268.img.bin"
    @glyph_0x8269:
    universal_glyph_header
        .incbin "graphics\glyphs\dumps\0x8269.img.bin"
    @glyph_0x826a:
    universal_glyph_header
        .incbin "graphics\glyphs\dumps\0x826a.img.bin"
    @glyph_0x826b:
    universal_glyph_header
        .incbin "graphics\glyphs\dumps\0x826b.img.bin"
    @glyph_0x826c:
    universal_glyph_header
        .incbin "graphics\glyphs\dumps\0x826c.img.bin"
    @glyph_0x826d:
    universal_glyph_header
        .incbin "graphics\glyphs\dumps\0x826d.img.bin"
    @glyph_0x826e:
    universal_glyph_header
        .incbin "graphics\glyphs\dumps\0x826e.img.bin"
    @glyph_0x826f:
    universal_glyph_header
        .incbin "graphics\glyphs\dumps\0x826f.img.bin"
    @glyph_0x8270:
    universal_glyph_header
        .incbin "graphics\glyphs\dumps\0x8270.img.bin"
    @glyph_0x8271:
    universal_glyph_header
        .incbin "graphics\glyphs\dumps\0x8271.img.bin"
    @glyph_0x8272:
    universal_glyph_header
        .incbin "graphics\glyphs\dumps\0x8272.img.bin"
    @glyph_0x8273:
    universal_glyph_header
        .incbin "graphics\glyphs\dumps\0x8273.img.bin"
    @glyph_0x8274:
    universal_glyph_header
        .incbin "graphics\glyphs\dumps\0x8274.img.bin"
    @glyph_0x8275:
    universal_glyph_header
        .incbin "graphics\glyphs\dumps\0x8275.img.bin"
    @glyph_0x8276:
    universal_glyph_header
        .incbin "graphics\glyphs\dumps\0x8276.img.bin"
    @glyph_0x8277:
    universal_glyph_header
        .incbin "graphics\glyphs\dumps\0x8277.img.bin"
    @glyph_0x8278:
    universal_glyph_header
        .incbin "graphics\glyphs\dumps\0x8278.img.bin"
    @glyph_0x8279:
    universal_glyph_header
        .incbin "graphics\glyphs\dumps\0x8279.img.bin"
    @glyph_0x8281:
    universal_glyph_header
        .incbin "graphics\glyphs\dumps\0x8281.img.bin"
    @glyph_0x8282:
    universal_glyph_header
        .incbin "graphics\glyphs\dumps\0x8282.img.bin"
    @glyph_0x8283:
    universal_glyph_header
        .incbin "graphics\glyphs\dumps\0x8283.img.bin"
    @glyph_0x8284:
    universal_glyph_header
        .incbin "graphics\glyphs\dumps\0x8284.img.bin"
    @glyph_0x8285:
    universal_glyph_header
        .incbin "graphics\glyphs\dumps\0x8285.img.bin"
    @glyph_0x8286:
    universal_glyph_header
        .incbin "graphics\glyphs\dumps\0x8286.img.bin"
    @glyph_0x8287:
    universal_glyph_header
        .incbin "graphics\glyphs\dumps\0x8287.img.bin"
    @glyph_0x8288:
    universal_glyph_header
        .incbin "graphics\glyphs\dumps\0x8288.img.bin"
    @glyph_0x8289:
    universal_glyph_header
        .incbin "graphics\glyphs\dumps\0x8289.img.bin"
    @glyph_0x828a:
    universal_glyph_header
        .incbin "graphics\glyphs\dumps\0x828a.img.bin"
    @glyph_0x828b:
    universal_glyph_header
        .incbin "graphics\glyphs\dumps\0x828b.img.bin"
    @glyph_0x828c:
    universal_glyph_header
        .incbin "graphics\glyphs\dumps\0x828c.img.bin"
    @glyph_0x828d:
    universal_glyph_header
        .incbin "graphics\glyphs\dumps\0x828d.img.bin"
    @glyph_0x828e:
    universal_glyph_header
        .incbin "graphics\glyphs\dumps\0x828e.img.bin"
    @glyph_0x828f:
    universal_glyph_header
        .incbin "graphics\glyphs\dumps\0x828f.img.bin"
    @glyph_0x8290:
    universal_glyph_header
        .incbin "graphics\glyphs\dumps\0x8290.img.bin"
    @glyph_0x8291:
    universal_glyph_header
        .incbin "graphics\glyphs\dumps\0x8291.img.bin"
    @glyph_0x8292:
    universal_glyph_header
        .incbin "graphics\glyphs\dumps\0x8292.img.bin"
    @glyph_0x8293:
    universal_glyph_header
        .incbin "graphics\glyphs\dumps\0x8293.img.bin"
    @glyph_0x8294:
    universal_glyph_header
        .incbin "graphics\glyphs\dumps\0x8294.img.bin"
    @glyph_0x8295:
    universal_glyph_header
        .incbin "graphics\glyphs\dumps\0x8295.img.bin"
    @glyph_0x8296:
    universal_glyph_header
        .incbin "graphics\glyphs\dumps\0x8296.img.bin"
    @glyph_0x8297:
    universal_glyph_header
        .incbin "graphics\glyphs\dumps\0x8297.img.bin"
    @glyph_0x8298:
    universal_glyph_header
        .incbin "graphics\glyphs\dumps\0x8298.img.bin"
    @glyph_0x8299:
    universal_glyph_header
        .incbin "graphics\glyphs\dumps\0x8299.img.bin"
    @glyph_0x829a:
    universal_glyph_header
        .incbin "graphics\glyphs\dumps\0x829a.img.bin"
    @glyph_0x8740:
    universal_glyph_header
        .incbin "graphics\glyphs\dumps\0x8740.img.bin"
    @glyph_0x8741:
    universal_glyph_header
        .incbin "graphics\glyphs\dumps\0x8741.img.bin"
    @glyph_0x8742:
    universal_glyph_header
        .incbin "graphics\glyphs\dumps\0x8742.img.bin"
    @glyph_0x8743:
    universal_glyph_header
        .incbin "graphics\glyphs\dumps\0x8743.img.bin"
    @glyph_0x8744:
    universal_glyph_header
        .incbin "graphics\glyphs\dumps\0x8744.img.bin"
    @glyph_0x8745:
    universal_glyph_header
        .incbin "graphics\glyphs\dumps\0x8745.img.bin"
    @glyph_0x8746:
    universal_glyph_header
        .incbin "graphics\glyphs\dumps\0x8746.img.bin"
    @glyph_0x8747:
    universal_glyph_header
        .incbin "graphics\glyphs\dumps\0x8747.img.bin"
    @glyph_0x8748:
    universal_glyph_header
        .incbin "graphics\glyphs\dumps\0x8748.img.bin"
    @glyph_0x8749:
    universal_glyph_header
        .incbin "graphics\glyphs\dumps\0x8749.img.bin"
    @glyph_0x874a:
    universal_glyph_header
        .incbin "graphics\glyphs\dumps\0x874a.img.bin"

NewWidthTable:
.byte 0x04, \
0x04, \
0x05, \
0x03, \
0x04, \
0x03, \
0x03, \
0x03, \
0x06, \
0x02, \
0x05, \
0x04, \
0x03, \
0x03, \
0x07, \
0x05, \
0x0D, \
0x0D, \
0x05, \
0x07, \
0x05, \
0x07, \
0x07, \
0x0C, \
0x07, \
0x0B, \
0x0C, \
0x0A, \
0x0D, \
0x04, \
0x0C, \
0x0C, \
0x0C, \
0x05, \
0x02, \
0x0B, \
0x09, \
0x03, \
0x03, \
0x06, \
0x06, \
0x05, \
0x05, \
0x05, \
0x05, \
0x04, \
0x04, \
0x05, \
0x05, \
0x05, \
0x05, \
0x06, \
0x06, \
0x05, \
0x05, \
0x06, \
0x06, \
0x05, \
0x05, \
0x08, \
0x08, \
0x08, \
0x08, \
0x0A, \
0x0A, \
0x09, \
0x09, \
0x09, \
0x08, \
0x08, \
0x0C, \
0x08, \
0x0A, \
0x08, \
0x04, \
0x03, \
0x05, \
0x0B, \
0x08, \
0x08, \
0x07, \
0x0A, \
0x0C, \
0x0A, \
0x08, \
0x08, \
0x0A, \
0x06, \
0x0C, \
0x0C, \
0x0C, \
0x0C, \
0x0C, \
0x0C, \
0x0C, \
0x0A, \
0x0A, \
0x0C, \
0x0C, \
0x0C, \
0x0C, \
0x0A, \
0x0A, \
0x0C, \
0x0C, \
0x06, \
0x06, \
0x0A, \
0x09, \
0x09, \
0x0A, \
0x0A, \
0x0A, \
0x0A, \
0x09, \
0x09, \
0x0A, \
0x0A, \
0x0A, \
0x0C, \
0x0C, \
0x0A, \
0x08, \
0x09, \
0x08, \
0x0C, \
0x07, \
0x0A, \
0x09, \
0x0A, \
0x0A, \
0x0A, \
0x0C, \
0x0C, \
0x0C, \
0x08, \
0x04, \
0x09, \
0x08, \
0x0C, \
0x09, \
0x05, \
0x07, \
0x06, \
0x06, \
0x06, \
0x0C, \
0x08, \
0x05, \
0x08, \
0x08, \
0x09, \
0x08, \
0x08, \
0x07, \
0x08, \
0x08, \
0x09, \
0x08, \
0x09, \
0x08, \
0x08, \
0x07, \
0x08, \
0x08, \
0x04, \
0x07, \
0x09, \
0x08, \
0x0A, \
0x08, \
0x0A, \
0x08, \
0x0A, \
0x08, \
0x08, \
0x08, \
0x08, \
0x0A, \
0x0C, \
0x09, \
0x0A, \
0x08, \
0x06, \
0x07, \
0x06, \
0x07, \
0x06, \
0x05, \
0x07, \
0x06, \
0x02, \
0x04, \
0x06, \
0x02, \
0x0A, \
0x06, \
0x07, \
0x07, \
0x07, \
0x05, \
0x07, \
0x05, \
0x06, \
0x06, \
0x0A, \
0x07, \
0x06, \
0x06, \
0x0E, \
0x0E, \
0x0E, \
0x0E, \
0x0E, \
0x0E, \
0x0E, \
0x0E, \
0x0E, \
0x0E, \
0x0E, \
0x00
.endregion